In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Files used in current analysis/Linkedin_Job_Details_26-Sep-2023-to-09-Oct-2023_4214-jobs_181-pages.csv')
df

,Job Title,Job Info,Job Type,Job Link,employees
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job
...,...,...,...,...,...
4209,Oracle Apps DBA - R12 (Full Customization),"Rozee.pk · Lahore, Punjab, Pakistan \n4 days ago",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3734517227,"501-1,000 employees"
4210,"Engineer, Service-to-Service Fabric",Atlassian · APAC Reposted \n3 days ago\n\n · ...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3730554639,"5,001-10,000 employees · Software Development"
4211,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting
4212,Senior IOS Developer,ekar · Pakistan \n4 days ago\n\n · 223 applic...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3736179533,"51-200 employees · Transportation, Logistics, ..."
4213,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting

In [3]:
df_=pd.read_csv('Files used in current analysis/Linkedin_Job-Descriptions-company_details_26-Sep-2023-to-26-Nov-2023_15947-jobs_685-pages.csv')
df_

,Job Link,Job Desception,Company Info
0,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...
15942,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN
15943,https://www.linkedin.com/jobs/view/3766809535,About the job\n \n \nA U.S.-based c...,IT Services and IT Consulting\n \n ...
15944,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
15945,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
15946,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [4]:
df_1=pd.read_csv('Files used in current analysis/Linkedin_Job_Details_26-Sep-2023-to-26-Nov-2023_15875-jobs_685-pages.csv')
df_1

,Job Title,Job Info,Job Type,Job Link,employees
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job
...,...,...,...,...,...
15870,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking"
15871,Release Support Engineer,Turing · Pakistan Reposted \n1 week ago,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3766809535,"1,001-5,000 employees · IT Services and IT Con..."
15872,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting
15873,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...
15874,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees

In [138]:
# i am looking for solution that if job_id of Job_details data frame  match with job_id of jobs_description data frame 
# then show jobs_description  with job_id of Job_details

In [139]:
df['Job ID']=df['Job Link'].apply(lambda x:int(x.split('/')[5]))
df_['Job ID']=df_['Job Link'].apply(lambda x:int(x.split('/')[5]))
df_1['Job ID']=df_1['Job Link'].apply(lambda x:int(x.split('/')[5]))

In [140]:
# x=np.array(df['Job ID'])
# y=np.array(df_['Job ID'])
# z=np.where(x==y)
# z

In [141]:
df_2=df_[df_['Job ID'].isin(df['Job ID'])]
df_2

,Job Link,Job Desception,Company Info,Job ID
0,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...,3727054368
1,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...,3723395858
2,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...,3727034665
3,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...,3727029273
4,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN,3727034696
...,...,...,...,...
15679,https://www.linkedin.com/jobs/view/3729723124,About the job\n \n \nJob Responsibi...,Software Development\n \n ...,3729723124
15681,https://www.linkedin.com/jobs/view/3537348803,About the job\n \n \nLOCATION: Jara...,NaN,3537348803
15766,https://www.linkedin.com/jobs/view/3661745501,About the job\n \n \nAbout Us:CureM...,Software Development\n \n ...,3661745501
15776,https://www.linkedin.com/jobs/view/3728757956,About the job\n \n \nAbout the role...,Book and Periodical Publishing\n \n...,3728757956
15915,https://www.linkedin.com/jobs/view/3734537706,About the job\n \n \nPosition Title...,Internet Marketplace Platforms\n \n...,3734537706

In [142]:
df_3=pd.merge(df,df_,on='Job ID',how='inner')
df_3

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
7267,"Engineer, Service-to-Service Fabric",Atlassian · APAC Reposted \n3 days ago\n\n · ...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3730554639,"5,001-10,000 employees · Software Development",3730554639,https://www.linkedin.com/jobs/view/3730554639,About the job\n \n\n \nOverviewWork...,Software Development\n \n ...
7268,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...
7269,Senior IOS Developer,ekar · Pakistan \n4 days ago\n\n · 223 applic...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3736179533,"51-200 employees · Transportation, Logistics, ...",3736179533,https://www.linkedin.com/jobs/view/3736179533,About the job\n \n\n \nAbout Ekar C...,"Transportation, Logistics, Supply Chain and St..."
7270,Senior IOS Developer,ekar · Pakistan \n4 days ago\n\n · 223 applic...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3736179533,"51-200 employees · Transportation, Logistics, ...",3736179533,https://www.linkedin.com/jobs/view/3736179533,About the job\n \n\n \nAbout Ekar C...,"Transportation, Logistics, Supply Chain and St..."
7271,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...

In [143]:
# why df3 have 7272 rows

In [144]:
# df3=df[df['Job ID']==df_['Job ID']]
# df3
# ValueError: Can only compare identically-labeled Series objects

In [145]:
df_2.drop_duplicates(subset=['Job ID']).shape

(3623, 4)

In [146]:
df.drop_duplicates(subset=['Job ID']).shape

(3623, 6)

In [147]:
df_3.drop_duplicates(subset=['Job ID']).shape

(3623, 9)

In [148]:
df.isnull().sum()

Job Title    54
Job Info     54
Job Type     54
Job Link      0
employees    54
Job ID        0
dtype: int64

In [149]:
df_3.isnull().sum()

Job Title          67
Job Info           67
Job Type           67
Job Link_x          0
employees          67
Job ID              0
Job Link_y          0
Job Desception    104
Company Info      915
dtype: int64

In [150]:
df_3.columns

Index(['Job Title', 'Job Info', 'Job Type', 'Job Link_x', 'employees',
       'Job ID', 'Job Link_y', 'Job Desception', 'Company Info'],
      dtype='object')

In [151]:
df.dropna(inplace=True)
df_1.dropna(inplace=True)
df_3.dropna(subset=['Job Title','Job Info','Job Type','employees'],inplace=True) # i want to delete specific columns

In [152]:
# df['Job ID']=df['Job Link'].apply(lambda x:int(x.split('/')[5]))

In [153]:
df = df.drop_duplicates(subset=['Job ID'])
df_1=df_1.drop_duplicates(subset=['Job ID'])
df_2=df_2.drop_duplicates(subset=['Job ID'])
df_3=df_3.drop_duplicates(subset=['Job ID'])

In [154]:
df.shape,df_1.shape,df_2.shape,df_3.shape

((3573, 6), (11744, 6), (3623, 4), (3573, 9))

In [155]:
df_2

,Job Link,Job Desception,Company Info,Job ID
0,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...,3727054368
1,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...,3723395858
2,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...,3727034665
3,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...,3727029273
4,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN,3727034696
...,...,...,...,...
4210,https://www.linkedin.com/jobs/view/3734517227,About the job\n \n\n \nJob Summary:...,Business Consulting and Services\n ...,3734517227
4211,https://www.linkedin.com/jobs/view/3730554639,About the job\n \n\n \nOverviewWork...,Software Development\n \n ...,3730554639
4212,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...,3731001750
4213,https://www.linkedin.com/jobs/view/3736179533,About the job\n \n\n \nAbout Ekar C...,"Transportation, Logistics, Supply Chain and St...",3736179533
4214,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...,3731006178

In [156]:
df_3

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
7266,Oracle Apps DBA - R12 (Full Customization),"Rozee.pk · Lahore, Punjab, Pakistan \n4 days ago",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3734517227,"501-1,000 employees",3734517227,https://www.linkedin.com/jobs/view/3734517227,About the job\n \n\n \nJob Summary:...,Business Consulting and Services\n ...
7267,"Engineer, Service-to-Service Fabric",Atlassian · APAC Reposted \n3 days ago\n\n · ...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3730554639,"5,001-10,000 employees · Software Development",3730554639,https://www.linkedin.com/jobs/view/3730554639,About the job\n \n\n \nOverviewWork...,Software Development\n \n ...
7268,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...
7269,Senior IOS Developer,ekar · Pakistan \n4 days ago\n\n · 223 applic...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3736179533,"51-200 employees · Transportation, Logistics, ...",3736179533,https://www.linkedin.com/jobs/view/3736179533,About the job\n \n\n \nAbout Ekar C...,"Transportation, Logistics, Supply Chain and St..."
7271,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...

In [157]:
# job IDs of df_2 and df_3 are same after removal of duplication but before droping null values

### analyzing jobs with tech keyword

In [158]:

it_tech_pattern = 'Tech'
filtered_df = df[df['Job Title'].str.contains(it_tech_pattern, case=False)]
filtered_df

,Job Title,Job Info,Job Type,Job Link,employees,Job ID
42,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702
47,Fintech B2B Marketing Executive,"IMarkPlace · Karachi Division, Sindh, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727001717,11-50 employees,3727001717
124,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728
155,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567
176,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223
...,...,...,...,...,...,...
3905,Senior Technical Writer,Pena · Pakistan (Remote) \n3 days ago,Full-time,https://www.linkedin.com/jobs/view/3731030545,1-10 employees,3731030545
3990,Strategic Business Unit – Technical & Business...,Sui Southern Gas Company Limited · Karachi Div...,Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3735940212,"5,001-10,000 employees · Utilities",3735940212
4014,"Electronic Technician (Sukkur, Pakistan)","SLB · Islamabad, Islāmābād, Pakistan \n4 days...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3730566199,"10,001+ employees · Technology, Information an...",3730566199
4211,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750
4213,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178

In [159]:
# it_tech_pattern = 'Tech'
# filtered_df = df_3[df_3['Job Title'].str.contains(it_tech_pattern, case=False)]
# filtered_df
# ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [160]:
it_tech_pattern = 'Tech'
filtered_df = df_3[df_3['Job Title'].str.contains(it_tech_pattern, case=False)]
filtered_df

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
112,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702,https://www.linkedin.com/jobs/view/3727039702,About the job\n \n\n \nEXPERIENCE: ...,Information Technology & Services\n ...
120,Fintech B2B Marketing Executive,"IMarkPlace · Karachi Division, Sindh, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727001717,11-50 employees,3727001717,https://www.linkedin.com/jobs/view/3727001717,About the job\n \n\n \nFintech B2B ...,Internet Marketplace Platforms\n \n...
232,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728,https://www.linkedin.com/jobs/view/3715439728,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
282,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567,https://www.linkedin.com/jobs/view/3727012567,About the job\n \n\n \nRoles & Resp...,Human Resources Services\n \n ...
303,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223,https://www.linkedin.com/jobs/view/3727011223,About the job\n \n\n \nAbout the jo...,Human Resources Services\n \n ...
...,...,...,...,...,...,...,...,...,...
6891,Senior Technical Writer,Pena · Pakistan (Remote) \n3 days ago,Full-time,https://www.linkedin.com/jobs/view/3731030545,1-10 employees,3731030545,https://www.linkedin.com/jobs/view/3731030545,About the job\n \n\n \nResponsibili...,IT Services and IT Consulting\n \n ...
7013,Strategic Business Unit – Technical & Business...,Sui Southern Gas Company Limited · Karachi Div...,Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3735940212,"5,001-10,000 employees · Utilities",3735940212,https://www.linkedin.com/jobs/view/3735940212,About the job\n \n\n \nEngineering ...,"Utilities\n \n 5,001-1..."
7060,"Electronic Technician (Sukkur, Pakistan)","SLB · Islamabad, Islāmābād, Pakistan \n4 days...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3730566199,"10,001+ employees · Technology, Information an...",3730566199,https://www.linkedin.com/jobs/view/3730566199,About the job\n \n\n \nElectronic T...,"Technology, Information and Internet\n ..."
7268,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...
7271,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...

In [161]:
# results of df_3 are same as for df

In [162]:
it_tech_pattern = 'Tech'
filtered_df_1 = df_1[df_1['Job Title'].str.contains(it_tech_pattern, case=False)]
filtered_df_1

,Job Title,Job Info,Job Type,Job Link,employees,Job ID
42,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702
47,Fintech B2B Marketing Executive,"IMarkPlace · Karachi Division, Sindh, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727001717,11-50 employees,3727001717
124,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728
155,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567
176,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223
...,...,...,...,...,...,...
15747,Senior Mechanical Technician,"MOL Group · Banda Daud Shah, Khyber Pakhtunkhw...",On-site\n\n \nFull-time\n\n \nAssociate,https://www.linkedin.com/jobs/view/3765634041,"10,001+ employees · Oil and Gas",3765634041
15761,Technical Drafter,Supreme Technocrafts Aviation Services · Islam...,Hybrid\n\n \nContract,https://www.linkedin.com/jobs/view/3768586578,11-50 employees,3768586578
15838,Senior Consultant / Assistant Manager- Busines...,"EY in Pakistan · Karachi Division, Sindh, Pak...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3768510563,"1,001-5,000 employees · Accounting",3768510563
15851,"Principal Software Engineer, IgniteTech (Remot...","Crossover · Karāchi, Sindh, Pakistan Reposted...",Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3766351795,"5,001-10,000 employees · IT Services and IT Co...",3766351795
15864,Technical Sales Support Specialist,"BUZZMAX.CA · Karāchi, Sindh, Pakistan \n1 wee...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3765162094,11-50 employees,3765162094

In [163]:
# 470 rows in df_1: total data

In [164]:
filtered_df['Job Title'].unique()
# checking if Teh then it is IT or not

array(['Technical Business Analyst', 'Fintech B2B Marketing Executive',
       'Senior Technical Support Engineer, Skyvera (Remote) - $30,000/year USD',
       'Technical Recruiter', 'ERP Technical Support',
       'Technical Content Writer',
       'ASSISTANT MANAGER COMPLIANCE- INFORMATION TECHNOLOGY',
       'Technical Writer', 'Dynamics 365 F&O Technical Consultant',
       'Technical Customer Support Specialist',
       'Technical Project Manager', 'Cloud Technical Specialist',
       'Technical Project Manager/ Scrum Master',
       'Engineering Technician', 'Radiologic Technologist',
       'Technical Lead - .NET', 'Senior Technical Project Manager',
       'Technical Advisor for Development of Women Entrepreneurship Policy - Islamabad',
       'Technical Product Manager',
       'Senior Technical Support Analyst, Skyvera (Remote) - $30,000/year USD',
       'Technical Advisor Environmental Health - Asia',
       'Technical Sales Representative',
       'Head of Technology and Mechanization - Agri',
       'Technical Team Lead, Trilogy (Remote) - $100,000/year USD',
       'Technical Lead .NET', 'Assistant Manager Technical Sales',
       'Technical Lead',
       'Cardiac Catheterization Laboratory Technologist',
       'Sr Associate Technical Client Support', 'Site Technician',
       'Talent Acquisition Specialist (Technical Recruiter)',
       'Technical Team Lead', 'Project Manager Technical Lead',
       'Technical Delivery Specialist – Microsoft Dynamics 365',
       'Senior Lay Equipment Technician',
       'Technical Lead ML DevOps Engineer',
       'Associate Technical Client Support', 'Tier 1 Support Technician',
       'Chief Technology Officer', 'Technical Support Specialist',
       'Technical Support Engineer, Skyvera (Remote) - $30,000/year USD',
       'Technical VFX Artist',
       'Solar Installation Technician (Project Based)',
       'Endoscopy Technician', 'Lead Technical Support Engineer',
       'Lead Generation Manager, Technology & Data Strategy',
       'Technical Project Manager (Evening Shift)',
       'DM Technical Performance',
       'Technology Consulting- SAP- EAM- Rapid Innovation',
       'Lead Generation Intern ( Technical )', 'Technical Manager',
       'Technical Support - Shopify',
       'Information Technology Business Partner', 'Tech Trainer',
       'Information Technology Functional Partner',
       'Information Technology Help Desk Manager',
       'Senior Technical Content Writer', 'Migration Technical Lead',
       'Pakistan CSA: Agricultural Technology Special',
       'Technical SEO Specialist', 'Laboratory Technician', 'Technician',
       'Plant Technician', 'Assistant Manager Technical Services',
       'Solar Inverter Repair Technician',
       'Fortify Lead Technical Consultant',
       'Information Technology Intern', 'Technical Doc Writer',
       'Technical Support Analyst, Skyvera (Remote) - $20,000/year USD',
       'Technical Support Representative, Skyvera (Remote) - $15,000/year USD',
       'Technical Product Owner, Trilogy (Remote) - $100,000/year USD',
       'Information Technology Sales Executive',
       'Information Technology Project Manager', 'Fintech Developer',
       'Food Technologist', 'MS Dynamics 365 F&O - Technical Architect',
       'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)',
       'Information Technology Support Engineer',
       'Technical Application Specialist - Molecular Diagnosis',
       'Technical Lead Frontend - UI',
       'Project Manager( FinTech) ( Forex Trading)',
       'Fintech Products B2B Marketer (Freelance)', 'Fullstack Tech Lead',
       'Technical Support Engineer, Developer Support',
       'Information Technology Business Analyst',
       'Technical Support Engineer', 'Ariba Techno/Functional Analyst',
       'Microsoft Dynamics 365 Technical Support, Power Platform',
       'Technical Associate Program 2023 - Excellent Opportunity for Fresh Graduates in Pakistan',
       'Trainee Technical Product Support Engineer',
       'Information Technology Coordinator - Sales',
       'Technical Support Executive',
       'Bilingual (French) Support Technician',
       'Technical Support Specialist, Skyvera (Remote) - $15,000/year USD',
       'D365 Technical Consultant', 'Technical Sales Engineer',
       'Commodities Technical Analyst',
       'Technical Specialist, (Peshawar), Pakistan',
       'Technical Lead - Software & AI', 'Technical Proposal Writer',
       'Oracle Fusion Technical Consultant',
       'Non Technical Project Manager',
       'Technical Support Engineer (Solar Inverter + EVCS + Portable Power Station）',
       'Information Technology Security Manager',
       'Senior Technical Writer',
       'Microsoft Dynamics Consultant (Technical)',
       'Strategic Business Unit – Technical & Business Resources',
       'Electronic Technician (Sukkur, Pakistan)',
       'Technical Product Manager (OTE $80,000/year USD), Sparkrock'],
      dtype=object)

In [165]:
filtered_df[:50]

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
112,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702,https://www.linkedin.com/jobs/view/3727039702,About the job\n \n\n \nEXPERIENCE: ...,Information Technology & Services\n ...
120,Fintech B2B Marketing Executive,"IMarkPlace · Karachi Division, Sindh, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727001717,11-50 employees,3727001717,https://www.linkedin.com/jobs/view/3727001717,About the job\n \n\n \nFintech B2B ...,Internet Marketplace Platforms\n \n...
232,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728,https://www.linkedin.com/jobs/view/3715439728,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
282,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567,https://www.linkedin.com/jobs/view/3727012567,About the job\n \n\n \nRoles & Resp...,Human Resources Services\n \n ...
303,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223,https://www.linkedin.com/jobs/view/3727011223,About the job\n \n\n \nAbout the jo...,Human Resources Services\n \n ...
314,Technical Content Writer,"Soft Nation Technologies · Karachi Division, S...",Full-time,https://www.linkedin.com/jobs/view/3727012713,51-200 employees,3727012713,https://www.linkedin.com/jobs/view/3727012713,About the job\n \n\n \nCompany Desc...,IT Services and IT Consulting\n \n ...
317,ASSISTANT MANAGER COMPLIANCE- INFORMATION TECH...,"HCMS Global · Karachi Division, Sindh, Pakista...",Full-time,https://www.linkedin.com/jobs/view/3727023040,51-200 employees,3727023040,https://www.linkedin.com/jobs/view/3727023040,About the job\n \n\n \nJob Descript...,Human Resources Services\n \n ...
351,Technical Writer,"Visnext Software Solutions · Lahore, Punjab, P...",Full-time,https://www.linkedin.com/jobs/view/3727010645/...,51-200 employees,3727010645,https://www.linkedin.com/jobs/view/3727010645,About the job\n \n\n \nVisnext Soft...,Software Development\n \n ...
364,Dynamics 365 F&O Technical Consultant,LITS SERVICES - Microsoft Dynamics 365 Partner...,Full-time,https://www.linkedin.com/jobs/view/3727011673/...,51-200 employees,3727011673,https://www.linkedin.com/jobs/view/3727011673,About the job\n \n\n \nHello Linked...,Information Technology & Services\n ...
448,Technical Customer Support Specialist,"CrecenTech Systems Private Limited · Lahore, P...",Full-time,https://www.linkedin.com/jobs/view/3727050790/...,201-500 employees,3727050790,https://www.linkedin.com/jobs/view/3727050790,About the job\n \n\n \nWe are seeki...,IT System Custom Software Development\n ...
496,Technical Project Manager,"Status 200 Pvt Ltd. · Lahore, Punjab, Pakista...",Full-time,https://www.linkedin.com/jobs/view/3728002496/...,11-50 employees,3728002496,https://www.linkedin.com/jobs/view/3728002496,About the job\n \n\n \nJob Title: T...,IT Services and IT Consulting\n \n ...
508,Cloud Technical Specialist,"Zones IT Solutions · Islamabad, Islāmābād, Pak...",Full-time,https://www.linkedin.com/jobs/view/3707088816/...,"501-1,000 employees · IT Services and IT Consu...",3707088816,https://www.linkedin.com/jobs/view/3707088816,About the job\n \n\n \nDescriptionP...,IT Services and IT Consulting\n \n ...
626,Technical Project Manager,"DynamoLogic Solutions · Islamabad, Islāmābād, ...",Full-time,https://www.linkedin.com/jobs/view/3727043979/...,51-200 employees,3727043979,https://www.linkedin.com/jobs/view/3727043979,About the job\n \n\n \nDynamologic ...,IT Services and IT Consulting\n \n ...
643,Technical Project Manager/ Scrum Master,"Melior ITS · Islamabad, Islāmābād, Pakistan (O...",Full-time,https://www.linkedin.com/jobs/view/3727006879/...,11-50 employees,3727006879,https://www.linkedin.com/jobs/view/3727006879,About the job\n \n\n \nMelior is se...,Software Development\n \n ...
654,Engineering Technician,"Syngenta · Karachi Division, Sindh, Pakistan (...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3727033404/...,"10,001+ employees · Farming",3727033404,https://www.linkedin.com/jobs/view/3727033404,About the job\n \n\n \nAccountabili...,"Farming\n \n 10,001+ e..."
791,Radiologic Technologist,Allama iqbal college of medical sciences · Ma...,Full-time,https://www.linkedin.com/jobs/view/3723327463/...,AWAIS AHMAD is hiring for this job,3723327463,https://www.linkedin.com/jobs/view/3723327463,About the job\n \n\n \nRADIOLOGY TE...,NaN
807,Technical Lead - .NET,VeriPark · Pakistan (Remote) \n2 weeks ago,Full-time · Associate,https://www.linkedin.com/jobs/view/3723399146/...,"501-1,000 employees · Software Development",3723399146,https://www.linkedin.com/jobs/view/3723399146,About the job\n \n\n \nWe are FinTe...,Software Development\n \n ...
834,Senior Technical Project Manager,"Speridian Technologies · Lahore, Punjab, Pakis...",Full-time,https://www.linkedin.com/jobs/view/3727064982/...,"1,001-5,000 employees",3727064982,https://www.linkedin.com/jobs/view/3727064982,About the job\n \n\n \nWe are hirin...,IT Services and IT Consulting\n \n ...
1043,Technical Advisor for Development of Women Ent...,"UN Women · Islamabad, Islāmābād, Pakistan (On-...",Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3725385930,"1,001-5,000 employees · International Affairs",3725385930,https://www.linkedin.com/jobs/view/3725385930,About the job\n \n\n \nBackgroundIn...,International Affairs\n \n ...
1051,Technical Content Writer,"Digitaez · Karāchi, Sindh, Pakistan (On-site) ...",Full-time,https://www.linkedin.com/jobs/view/3727539416,11-50 employees,3727539416,https://www.linkedin.com/jobs/view/3727539416,About the job\n \n\n \nRole Descrip...,Information Technology & Services\n ...
1080,Technical Product Manager,"Noetic Technologies · Rawalpindi, Punjab, Paki...",Full-time,https://www.linkedin.com/jobs/view/3727521979,11-50 employees,3727521979,https://www.linkedin.com/jobs/view/3727521979,About the job\n \n\n \nResponsibili...,Telecommunications\n \n ...
1087,Technical Content Writer,"PureLogics · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727522396,201-500 employees,3727522396,https://www.linkedin.com/jobs/view/3727522396,About the job\n \n\n \nPureLogics i...,Software Development\n \n ...
1179,"Senior Technical Support Analyst, Skyvera (Rem...","Crossover · Lahore, Punjab, Pakistan (Remote)...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727368854,"5,001-10,000 employees · IT Services and IT Co...",3727368854,https://www.linkedin.com/jobs/view/3727368854,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
1263,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Lahore, Punjab, Pakistan (Remote)...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727374000,"5,001-10,000 employees · IT Services and IT Co...",3727374000,https://www.linkedin.com/jobs/view/3727374000,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
1280,Technical Advisor Environmental Health - Asia,"International Rescue Committee · Islamabad, Is...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3679509233,"5,001-10,000 employees · Non-profit Organizati...",3679509233,https://www.linkedin.com/jobs/view/3679509233,About the job\n \n\n \nRequisition ...,Non-profit Organization Management\n ...
1295,Technical Sales Representative,"Ibix Global Tech · Karāchi, Sindh, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727541829,51-200 employees,3727541829,https://www.linkedin.com/jobs/view/3727541829,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
1331,Head of Technology and Mechanization - Agri,"HRSG - Innovative Business Solutions · Lahore,...",Full-time,https://www.linkedin.com/jobs/view/3728792371,"10,001+ employees",3728792371,https://www.linkedin.com/jobs/view/3728792371,About the job\n \n\n \nJob Title: H...,Human Resources Services\n \n ...
1343,"Technical Team Lead, Trilogy (Remote) - $100,0...","Crossover · Rawalpindi, Punjab, Pakistan (Rem...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3727367888,"5,001-10,000 employees · IT Services and IT Co...",3727367888,https://www.linkedin.com/jobs/view/3727367888,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
1384,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Lahore, Punjab, Pakistan (Remote)...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727368849,"5,001-10,000 employees · IT Services and IT Co...",3727368849,https://www.linkedin.com/jobs/view/3727368849,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
1395,Technical Lead .NET,"DPL · Islamabad, Islāmābād, Pakistan (Hybrid) ...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3728317046,51-200 employees · IT Services and IT Consulting,3728317046,https://www.linkedin.com/jobs/view/3728317046,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
1530,Assistant Manager Technical Sales,"Captain & Company · Karāchi, Sindh, Pakistan (...",Full-time,https://www.linkedin.com/jobs/view/3727508822,11-50 employees,3727508822,https://www.linkedin.com/jobs/view/3727508822,About the job\n \n\n \nJob descript...,Chemical Manufacturing\n \n ...
1546,Technical Lead,"Orcalo Holdings · Rawalpindi, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727520777,201-500 employees,3727520777,https://www.linkedin.com/jobs/view/3727520777,About the job\n \n\n \nOrcalo Holdi...,IT Services and IT Consulting\n \n ...
1613,Cardiac Catheterization Laboratory Technologist,"National Medical Centre · Karāchi, Sindh, Paki...",Full-time,https://www.linkedin.com/jobs/view/3727372921,"1,001-5,000 employees",3727372921,https://www.linkedin.com/jobs/view/3727372921,About the job\n \n\n \nDiploma + Ex...,Hospitals and Health Care\n \n ...
1626,Sr Associate Technical Client Support,"S&P Global · Islamabad, Islāmābād, Pakistan (O...",Full-time,https://www.linkedin.com/jobs/view/3729164639,"10,001+ employees · Financial Services",3729164639,https://www.linkedin.com/jobs/view/3729164639,About the job\n \n\n \nThe Role: As...,Financial Services\n \n ...
1671,"Senior Technical Support Analyst, Skyvera (Rem...","Crossover · Lahore, Punjab, Pakistan (Remote)...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727367824,"5,001-10,000 employees · IT Services and IT Co...",3727367824,https://www.linkedin.com/jobs/view/3727367824,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
1717,Cloud Technical Specialist,"Zones IT Solutions · Islamabad, Islāmābād, Pak...",Full-time,https://www.linkedin.com/jobs/view/3720211981,"501-1,000 employees · IT Services and IT Consu...",3720211981,https://www.linkedin.com/jobs/view/3720211981,About the job\n \n\n \nDescriptionP...,IT Services and IT Consulting\n \n ...
1943,Site Technician,"SkyElectric Pvt. Ltd · Lahore, Punjab, Pakista...",Full-time,https://www.linkedin.com/jobs/view/3727996869,"501-1,000 employees",3727996869,https://www.linkedin.com/jobs/view/3727996869,About the job\n \n\n \nA Site Techn...,Renewable Energy Semiconductor Manufacturing\n...
2031,Talent Acquisition Specialist (Technical Recru...,"MobiTising Inc · Karāchi, Sindh, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3673688362,11-50 employees,3673688362,https://www.linkedin.com/jobs/view/3673688362,About the job\n \n\n \n🚀 Recruiter ...,Marketing Services\n \n ...
2042,Technical Team Lead,"ContentStudio.io · Islāmābād, Pakistan (On-sit...",Full-time,https://www.linkedin.com/jobs/view/3727986319,51-200 employees,3727986319,https://www.linkedin.com/jobs/view/3727986319,About the job\n \n\n \nCompany Desc...,"Technology, Information and Internet\n ..."
2045,Technical Recruiter,"Systems Limited · Lahore, Punjab, Pakistan (On...",Full-time,https://www.linkedin.com/jobs/view/3727926692,"5,001-10,000 employees",3727926692,https://www.linkedin.com/jobs/view/3727926692,About the job\n \n\n \nJoin our tea...,IT Services and IT Consulting\n \n ...
2070,Project Manager Technical Lead,"SPARK · Lahore, Punjab, Pakistan (Hybrid) \n1...",Full-time,https://www.linkedin.com/jobs/view/3727937161,11-50 employees,3727937161,https://www.linkedin.com/jobs/view/3727937161,About the job\n \n\n \nWe are looki...,"Technology, Information and Internet\n ..."
2102,Technical Content Writer,"Confiz · Lahore, Punjab, Pakistan (On-site) \...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3728219542,"501-1,000 employees · IT Services and IT Consu...",3728219542,https://www.linkedin.com/jobs/view/3728219542,About the job\n \n\n \nConfiz is lo...,IT Services and IT Consulting\n \n ...
2115,Technical Delivery Specialist – Microsoft Dyna...,"KAISPE · Karāchi, Sindh, Pakistan (On-site) \...",Full-time,https://www.linkedin.com/jobs/view/3728218445,11-50 employees,3728218445,https://www.linkedin.com/jobs/view/3728218445,About the job\n \n\n \nKey Responsi...,Software Development\n \n ...
2156,Senior Lay Equipment Technician,Kuiper Group · South Asia (Remote) \n1 week a...,Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3729504999,"1,001-5,000 employees · Oil and Gas",3729504999,https://www.linkedin.com/jobs/view/3729504999,About the job\n \n\n \nSenior Elect...,"Oil and Gas\n \n 1,001..."
2239,Technical Lead ML DevOps Engineer,"Motive · Islamabad, Islāmābād, Pakistan (Remot...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3676519207,"1,001-5,000 employees · Software Development",3676519207,https://www.linkedin.com/jobs/view/3676519207,About the job\n \n\n \nWho We AreMo...,Software Development\n \n ...
2246,Associate Technical Client Support,"S&P Global · Islamabad, Islāmābād, Pakistan (O...",Full-time,https://www.linkedin.com/jobs/view/3730054413,"10,001+ employees · Financial Services",3730054413,https://www.linkedin.com/jobs/view/3730054413,About the job\n \n\n \nThe Role: As...,Financial Services\n \n ...
2301,Tier 1 Support Technician,"TCP Software · Lahore, Punjab, Pakistan (On-si...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3707528067,"501-1,000 employees · Software Development",3707528067,https://www.linkedin.com/jobs/view/3707528067,About the job\n \n\n \nTCP is commi...,Software Development\n \n ...
2323,Engineering Technician,"Syngenta · Karachi Division, Sindh, Pakistan (...",Full-time · Mid-Senior level,https://www.linkedin.com/jobs/view/3724259794,"10,001+ employees · Farming",3724259794,https://www.linkedin.com/jobs/view/3724259794,About the job\n \n\n \nCompany Desc...,"Farming\n \n 10,001+ e..."
2430,Chief Technology Officer,"University of South Asia · Lahore, Punjab, Pak...",Full-time,https://www.linkedin.com/jobs/view/3730217023,201-500 employees,3730217023,https://www.linkedin.com/jobs/view/3730217023,About the job\n \n\n \nAbout the Or...,Education Administration Programs\n ...
2731,Technical Support Specialist,"Zones IT Solutions · Islamabad, Islāmābād, Pak...",Full-time,https://www.linkedin.com/jobs/view/3696213557,"501-1,000 employees · IT Services and IT Consu...",3696213557,https://www.linkedin.com/jobs/view/3696213557,About the job\n \n\n \nDescriptionP...,IT Services and IT Consulting\n \n ...

In [166]:
# #Engineering Technician
# df_[df_['Job ID']==3727033404]['Job Desception']
# df_['Job Desception'].iloc[405]

In [167]:
# # Radiologic Technologist
# df_[df_['Job ID']==3723327463]['Job Desception']
# df_['Job Desception'].iloc[502]

In [168]:
# # Technical Advisor for Development of Women Ent.
# df_[df_['Job ID']==3725385930]['Job Desception']
# df_['Job Desception'].iloc[661]

In [169]:
# 'computer' in df_['Job Desception'].iloc[661]

In [170]:
# # Head of Technology and Mechanization - Agri
# df_[df_['Job ID']==3728792371]['Job Desception']
# df_['Job Desception'].iloc[824]

In [171]:
# 'computer' in df_['Job Desception'].iloc[824]

In [172]:
# #Assistant Manager Technical Sales
# df_[df_['Job ID']==3727508822]['Job Desception']
# df_['Job Desception'].iloc[872]

In [173]:
# #Technical Lead this is IT job
# df_[df_['Job ID']==3727520777]['Job Desception']
# df_['Job Desception'].iloc[880]

In [174]:
# 'computer' in df_['Job Desception'].iloc[880]

In [175]:
# #Cardiac Catheterization Laboratory Technologist
# df_[df_['Job ID']==3727372921]['Job Desception']
# df_['Job Desception'].iloc[911]

In [176]:
# #Site Technician 
# #construction
# df_[df_['Job ID']==3727996869]['Job Desception']
# df_['Job Desception'].iloc[998]

In [177]:
# #Technical Team Lead this is IT job
# #Computer Science
# df_[df_['Job ID']==3727986319]['Job Desception']
# df_['Job Desception'].iloc[1097]

In [178]:
# #Technical Delivery Specialist – Microsoft Dyna...
# # not specified
# df_[df_['Job ID']==3728218445]['Job Desception']
# df_['Job Desception'].iloc[1164]

In [179]:
# 'software' in df_['Job Desception'].iloc[1164]

In [180]:
# # Chief Technology Officer
# # computer science
# df_[df_['Job ID']==3730217023]['Job Desception']
# df_['Job Desception'].iloc[1288]

In [181]:
# when Tech keyword is used then there are some non IT and computer jobs also

In [182]:
it_keywords=['computer','information technology','software','network','cybersecurity','developer','programming']# also add IT

In [183]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:3]:
    if 'computer' in job_desc:
        n_IT_jobs=n_IT_jobs+1

In [184]:
n_IT_jobs

0

In [185]:
'Computer' in filtered_df['Job Desception'].iloc[0]

True

In [186]:
'software' in filtered_df['Job Desception'].iloc[0]

True

In [187]:
'information technology' in filtered_df['Job Desception'].iloc[0]

False

In [188]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:50]:
    if 'computer' or 'information technology' in job_desc:
        n_IT_jobs=n_IT_jobs+1
n_IT_jobs
# here r operator is not working correct

50

In [189]:
# i=0
# IT_jobs=[]
# n_IT_jobs=0
# for job_desc in filtered_df['Job Desception'].iloc[:]:
#     if 'computer' in job_desc:
#         n_IT_jobs=n_IT_jobs+1
#     i=i+1
# n_IT_jobs
# # TypeError: argument of type 'float' is not iterable
# i
# filtered_df.iloc[123]

In [190]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'computer' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

26

In [191]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'Computer' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

33

In [192]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'software' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

79

In [193]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'Software' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

20

In [194]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'network' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

12

In [195]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'Cybersecurity' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

0

In [196]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'programming' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

13

In [197]:
IT_jobs=[]
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    try:
        if 'developer' in job_desc:
            n_IT_jobs=n_IT_jobs+1
    except TypeError:
        #print('null value')
        pass
    
n_IT_jobs

32

In [198]:
it_keywords=['computer','information technology','software','network','cybersecurity','developer','programming']
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    flag=0
    for keyword in it_keywords:
        try:
            if keyword in job_desc:
                flag=1
        except TypeError:
        #print('null value')
            pass
    if flag==1:
        n_IT_jobs=n_IT_jobs+1

n_IT_jobs

102

In [199]:
it_keywords=['computer','Computer','information technology','Information Technology','IT','software',
             'Software','network','Network','cybersecurity','Cybersecurity','developer',
             'Developer','programming','Programming']
n_IT_jobs=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    flag=0
    for keyword in it_keywords:
        try:
            if keyword in job_desc:
                flag=1
        except TypeError:
        #print('null value')
            pass
    if flag==1:
        n_IT_jobs=n_IT_jobs+1

print(n_IT_jobs)
# print(filtered_df['Job Desception'].isnull().sum())
# count_of_abnormal_desc=0
# for i in range(0,len(filtered_df)):
#     try:
#         if(len(filtered_df.iloc[i]['Job Desception'])<20):
#             # print(df.iloc[i])
#             count_of_abnormal_desc=count_of_abnormal_desc+1
#     except TypeError:
#         pass
#         # print('non value')
# if count_of_abnormal_desc==0:
#     print("Not Found any uncomplete job descreption")
# print(count_of_abnormal_desc)

# as out of 150 jobs with tech keywords 123 are IT jobs despite there are three 
# null and uncomplete jobs descriptions

123

In [200]:
it_keywords=['computer','Computer','information technology','Information Technology','IT','software',
             'Software','network','Network','cybersecurity','Cybersecurity','developer',
             'Developer','programming','Programming','virtual','Virtual','Data','data','Digital','digital','AI','web']
IT_jobs_IDs=[]
n_IT_jobs=0
loc=0
for job_desc in filtered_df['Job Desception'].iloc[:]:
    flag=0
    for keyword in it_keywords:
        try:
            if keyword in job_desc:
                flag=1
        except TypeError:
        #print('null value')
            pass
    if flag==1:
        n_IT_jobs=n_IT_jobs+1
        IT_jobs_IDs.append(filtered_df['Job ID'].iloc[loc])
        # filtered_df.iloc[5]['Job ID'] and filtered_df['Job ID'].iloc[5] are similar
    
    loc=loc+1

# print(n_IT_jobs)
# len(IT_jobs_IDs)
filtered_df_IT=filtered_df[filtered_df['Job ID'].isin(IT_jobs_IDs)]
filtered_df_IT

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
112,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702,https://www.linkedin.com/jobs/view/3727039702,About the job\n \n\n \nEXPERIENCE: ...,Information Technology & Services\n ...
232,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728,https://www.linkedin.com/jobs/view/3715439728,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
282,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567,https://www.linkedin.com/jobs/view/3727012567,About the job\n \n\n \nRoles & Resp...,Human Resources Services\n \n ...
303,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223,https://www.linkedin.com/jobs/view/3727011223,About the job\n \n\n \nAbout the jo...,Human Resources Services\n \n ...
314,Technical Content Writer,"Soft Nation Technologies · Karachi Division, S...",Full-time,https://www.linkedin.com/jobs/view/3727012713,51-200 employees,3727012713,https://www.linkedin.com/jobs/view/3727012713,About the job\n \n\n \nCompany Desc...,IT Services and IT Consulting\n \n ...
...,...,...,...,...,...,...,...,...,...
6891,Senior Technical Writer,Pena · Pakistan (Remote) \n3 days ago,Full-time,https://www.linkedin.com/jobs/view/3731030545,1-10 employees,3731030545,https://www.linkedin.com/jobs/view/3731030545,About the job\n \n\n \nResponsibili...,IT Services and IT Consulting\n \n ...
7013,Strategic Business Unit – Technical & Business...,Sui Southern Gas Company Limited · Karachi Div...,Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3735940212,"5,001-10,000 employees · Utilities",3735940212,https://www.linkedin.com/jobs/view/3735940212,About the job\n \n\n \nEngineering ...,"Utilities\n \n 5,001-1..."
7060,"Electronic Technician (Sukkur, Pakistan)","SLB · Islamabad, Islāmābād, Pakistan \n4 days...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3730566199,"10,001+ employees · Technology, Information an...",3730566199,https://www.linkedin.com/jobs/view/3730566199,About the job\n \n\n \nElectronic T...,"Technology, Information and Internet\n ..."
7268,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...
7271,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...

In [201]:
# it_tech_pattern = 'computer|information technology|software|network|cybersecurity|developer|programming'
# try:
#     filtered_df_IT_1 = filtered_df[filtered_df['Job Desception'].str.contains(it_tech_pattern, case=False)]
# except ValueError:
#     print('null value')
# filtered_df_IT_1
# NameError: name 'filtered_df_IT_1' is not defined

In [202]:
filtered_df.dropna(subset=['Job Desception'],inplace=True)
# filtered_df
it_tech_pattern = 'computer|information technology|software|network|cybersecurity|developer|programming'
filtered_df_IT_1 = filtered_df[filtered_df['Job Desception'].str.contains(it_tech_pattern, case=False)]
filtered_df_IT_1
# by this method there are 4 less rows

C:\Users\BILAL.COM\AppData\Local\Temp\ipykernel_5192\3666492737.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.dropna(subset=['Job Desception'],inplace=True)

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
112,Technical Business Analyst,"UHF Solutions Pvt Ltd · Karachi Division, Sind...",Internship,https://www.linkedin.com/jobs/view/3727039702,51-200 employees,3727039702,https://www.linkedin.com/jobs/view/3727039702,About the job\n \n\n \nEXPERIENCE: ...,Information Technology & Services\n ...
232,"Senior Technical Support Engineer, Skyvera (Re...","Crossover · Peshawar, Khyber Pakhtunkhwa, Pak...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3715439728,"5,001-10,000 employees · IT Services and IT Co...",3715439728,https://www.linkedin.com/jobs/view/3715439728,About the job\n \n\n \nCrossover is...,IT Services and IT Consulting\n \n ...
282,Technical Recruiter,"HR Force Int. · Lahore, Punjab, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3727012567,11-50 employees · Human Resources Services,3727012567,https://www.linkedin.com/jobs/view/3727012567,About the job\n \n\n \nRoles & Resp...,Human Resources Services\n \n ...
303,ERP Technical Support,HR Ways - Hiring Tech Talent · Karachi Divisio...,Full-time,https://www.linkedin.com/jobs/view/3727011223,11-50 employees,3727011223,https://www.linkedin.com/jobs/view/3727011223,About the job\n \n\n \nAbout the jo...,Human Resources Services\n \n ...
314,Technical Content Writer,"Soft Nation Technologies · Karachi Division, S...",Full-time,https://www.linkedin.com/jobs/view/3727012713,51-200 employees,3727012713,https://www.linkedin.com/jobs/view/3727012713,About the job\n \n\n \nCompany Desc...,IT Services and IT Consulting\n \n ...
...,...,...,...,...,...,...,...,...,...
6891,Senior Technical Writer,Pena · Pakistan (Remote) \n3 days ago,Full-time,https://www.linkedin.com/jobs/view/3731030545,1-10 employees,3731030545,https://www.linkedin.com/jobs/view/3731030545,About the job\n \n\n \nResponsibili...,IT Services and IT Consulting\n \n ...
7013,Strategic Business Unit – Technical & Business...,Sui Southern Gas Company Limited · Karachi Div...,Contract · Mid-Senior level,https://www.linkedin.com/jobs/view/3735940212,"5,001-10,000 employees · Utilities",3735940212,https://www.linkedin.com/jobs/view/3735940212,About the job\n \n\n \nEngineering ...,"Utilities\n \n 5,001-1..."
7060,"Electronic Technician (Sukkur, Pakistan)","SLB · Islamabad, Islāmābād, Pakistan \n4 days...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3730566199,"10,001+ employees · Technology, Information an...",3730566199,https://www.linkedin.com/jobs/view/3730566199,About the job\n \n\n \nElectronic T...,"Technology, Information and Internet\n ..."
7268,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 144...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731001750,51-200 employees · IT Services and IT Consulting,3731001750,https://www.linkedin.com/jobs/view/3731001750,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...
7271,"Technical Product Manager (OTE $80,000/year US...",Sparkrock · South Asia \n4 days ago\n\n · 137...,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3731006178,51-200 employees · IT Services and IT Consulting,3731006178,https://www.linkedin.com/jobs/view/3731006178,About the job\n \n\n \nAre you a hi...,IT Services and IT Consulting\n \n ...

### building Function for automatic keywords checking

#### making logic

In [203]:
# it_tech_keywords = ['IT']


# df_3_IT =df_3[df_3['Job Title'].apply(lambda title: any(keyword in title for keyword in it_tech_keywords))]
# df_3_IT
# len(df_3_IT)
# df_3_IT['Job Title'].unique()
# # len(df_3_IT['Job Title'].unique())
# #100% IT jobs

In [204]:
# it_tech_pattern = 'IT'
# filtered_df_title = df_3[df_3['Job Title'].str.contains(it_tech_pattern, case=False)]
# print(f'length of filtered_df_title:{len(filtered_df_title)}\n\n')
# print(f'Unique values in filtered_df_title:\n{filtered_df_title["Job Title"].unique()}\n\n')
# print(f'Number of Unique values in filtered_df_title:{len(filtered_df_title["Job Title"].unique())}\n\n')
# filtered_df_title['Job Desception'].isnull().sum()
# count_of_un_complete_desc=0
# for i in range(0,len(filtered_df_title)):
#     try:
#         if(len(filtered_df_title.iloc[i]['Job Desception'])<20):
#             # print(df.iloc[i])
#             count_of_un_complete_desc=count_of_un_complete_desc+1
#     except TypeError:
#         pass
#         # print('non value')
# if count_of_un_complete_desc==0:
#     print("Not Found any uncomplete job descreption")
# n_abnormal_desc=count_of_un_complete_desc+filtered_df_title['Job Desception'].isnull().sum()
# print(f"count of_un_complete_desc in filtered_df_title:{count_of_un_complete_desc}")
# print(f"count of Null desc in filtered_df_title:{filtered_df_title['Job Desception'].isnull().sum()}")
# print(f"count of abonormal desc in filtered_df_title:{n_abnormal_desc}\n\n")
# # filtered_df_title

In [205]:
# filtered_df_title['Job Desception'].isnull().sum()
# count_of_un_complete_desc=0
# for i in range(0,len(filtered_df_title)):
#     try:
#         if(len(filtered_df_title.iloc[i]['Job Desception'])<20):
#             # print(df.iloc[i])
#             count_of_un_complete_desc=count_of_un_complete_desc+1
#     except TypeError:
#         pass
#         # print('non value')
# if count_of_un_complete_desc==0:
#     print("Not Found any uncomplete job descreption")
# n_abnormal_desc=count_of_un_complete_desc+filtered_df_title['Job Desception'].isnull().sum()
# print(f"count of_un_complete_desc in filtered_df_title:{count_of_un_complete_desc}")
# print(f"count of Null desc in filtered_df_title:{filtered_df_title['Job Desception'].isnull().sum()}")
# print(f"count of abonormal desc in filtered_df_title:{n_abnormal_desc}\n\n")

In [206]:
# len(filtered_df_title)

In [207]:
# filtered_df_title.iloc[513]
# filtered_df_title.iloc[513]['Job Desception']
# it works correctly

In [208]:
# filtered_df_title[filtered_df_title['Job Title']=='Assistant Manager - Quality']['Job Desception']

***for one keyword there are two descriptions***

In [209]:
# filtered_df_title[filtered_df_title['Job Title']=='Assistant Manager - Quality']['Job Desception'].isnull().sum()

In [210]:
# filtered_df_title[filtered_df_title['Job Title']=='Assistant Manager - Quality']['Job Desception'].isnull().sum()==1

In [211]:
# len(str(filtered_df_title[filtered_df_title['Job Title']=='Assistant Manager - Quality']['Job Desception']))<64

In [212]:
# filtered_df_title.tail()

***work on rest_index***

In [213]:
# it_keywords=['computer','Computer','information technology','Information Technology','IT','software',
#              'Software','network','Network','cybersecurity','Cybersecurity','developer',
#              'Developer','programming','Programming','virtual','Virtual','Data','data','Digital','digital','AI','web']
# IT_jobs_IDs=[]
# n_IT_jobs=0
# loc=0
# for job_desc in filtered_df_title['Job Desception'].iloc[:]:
#     flag=0
#     for keyword in it_keywords:
#         try:
#             if keyword in job_desc:
#                 flag=1
#         except TypeError:
#         #print('null value')
#             pass
#     if flag==1:
#         n_IT_jobs=n_IT_jobs+1
#         IT_jobs_IDs.append(filtered_df_title['Job ID'].iloc[loc])
#         # filtered_df.iloc[5]['Job ID'] and filtered_df['Job ID'].iloc[5] are similar
    
#     loc=loc+1

# n_IT_jobs
# len(IT_jobs_IDs)
# filtered_df_desc=filtered_df_title[filtered_df_title['Job ID'].isin(IT_jobs_IDs)]

# print(f'length of filtered_df_desc:{len(filtered_df_desc)}\n\n')
# print(f'Unique values in filtered_df_title:\n{filtered_df_desc["Job Title"].unique()}\n\n')
# print(f"Number of Unique values in filtered_df_desc:{len(filtered_df_desc['Job Title'].unique())}\n\n")

# if len(filtered_df_desc)+n_abnormal_desc==len(filtered_df_title):
#     print('100 % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
# else:
#     percent=(len(filtered_df_desc)+n_abnormal_desc)/len(filtered_df_title)
#     print(f'{percent} % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
# # filtered_df_desc

In [214]:
# defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
# for value in filtered_df_title['Job Title'].unique():
#     if value not in filtered_df_desc["Job Title"].unique():
#         defferences.append(value) 
# print(f'list of job titles which present in filtered_df_title but not present in filtered_df_desc:\n\n{defferences}\n\n')

In [215]:
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']

In [216]:
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception']==np.nan
# str(filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'])
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception']==None
# 'NaN'==np.nan
# np.nan
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'].dtype
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'].isnull()
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'].isnull()==True
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'].isnull().sum()
# filtered_df_title[filtered_df_title['Job Title']=='IT Sales Executive']['Job Desception'].isnull().sum()==1
# filtered_df_title[filtered_df_title['Job Title']=='Team Lead IT Software Development (m/f/d)']['Job Desception'].isnull().sum()==1

In [217]:
# defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
# defferences1=[] # List of titles that are not cleared as IT and Tech Job due to abnoramal desc
# for value in filtered_df_title['Job Title'].unique():
#     if value not in filtered_df_desc["Job Title"].unique():
#         defferences.append(value)
#         if filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception'].isnull().sum()==1:
#            defferences1.append(value) 
        
# print(f'list of job titles which present in filtered_df_title but not present in filtered_df_desc:\n\n{defferences}\n\n')
# print(f'List of titles that are not cleared as IT and Tech Job due to abnoramal desc:\n\n{defferences1}\n\n')
# # not uncomplete but null

In [218]:
# filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']
# filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']
# len(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']) # I am facing problem to show actual value
# str(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception'])
# len(str(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']))
# len('About the job')
# len('6960    \nName: Job Desception, dtype: object') # it means i have to do 20+44
# 20+44
# len(str(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']))<64

In [219]:
# defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
# defferences1=[] # List of titles that are not cleared as IT and Tech Job due to abnoramal desc
# for value in filtered_df_title['Job Title'].unique():
#     if value not in filtered_df_desc["Job Title"].unique():
#         defferences.append(value)
#         if filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception'].isnull().sum()==1:
#            defferences1.append(value)
#         elif len(str(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']))<64:
#            defferences1.append(value)
        
# print(f'list of job titles which present in filtered_df_title but not present in filtered_df_desc:\n\n{defferences}\n\n')
# print(f'List of titles that are not cleared as IT and Tech Job due to abnoramal desc:\n\n{defferences1}\n\n')

In [220]:
# defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
# defferences1=[] # List of titles that are not cleared as IT and Tech Job due to abnoramal desc
# defferences2=[] # List of titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc
# for value in filtered_df_title['Job Title'].unique():
#     if value not in filtered_df_desc["Job Title"].unique():
#         defferences.append(value)
#         if filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception'].isnull().sum()==1:
#            defferences1.append(value)
#         elif len(str(filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception']))<64:
#            defferences1.append(value)
#         else:
#             defferences2.append(value)
            
        
# print(f'list of {len(defferences)} job titles which present in filtered_df_title but not present in filtered_df_desc:\n{defferences}\n\n')
# print(f'List of {len(defferences1)} titles that are not cleared as IT and Tech Job due to abnoramal desc:\n{defferences1}\n\n')
# print(f'List of  {len(defferences2)} titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:\n{defferences2}\n\n')

#### actual function

In [245]:
#### building logic for one word in description
def filter_desc_by_one_keyword(df_3,it_tech_pattern,case):
    df_4=df_3.dropna(subset=['Job Desception'])
    filtered_df= df_4[df_4['Job Desception'].str.contains(it_tech_pattern, case)]
    it_keywords=['computer','Computer','information technology','Information Technology','IT','software',
             'Software','network','Network','cybersecurity','Cybersecurity','developer',
             'Developer','programming','Programming','virtual','Virtual','Data','data','Digital','digital','AI','web']
    IT_jobs_IDs=[]
    n_IT_jobs=0
    loc=0
    for job_desc in filtered_df['Job Desception'].iloc[:]:
        flag=0
        for keyword in it_keywords:
            try:
                if keyword in job_desc:
                    flag=1
            except TypeError:
            #print('null value')
                pass
        if flag==1:
            n_IT_jobs=n_IT_jobs+1
            IT_jobs_IDs.append(filtered_df['Job ID'].iloc[loc])
            # filtered_df.iloc[5]['Job ID'] and filtered_df['Job ID'].iloc[5] are similar
        
        loc=loc+1
    
    n_IT_jobs
    len(IT_jobs_IDs)
    filtered_df_desc=filtered_df[filtered_df['Job ID'].isin(IT_jobs_IDs)]
    
    print(f'length of filtered_df_desc:{len(filtered_df_desc)}\n\n')
    print(f'Unique values in filtered_df_desc:\n{filtered_df_desc["Job Title"].unique()}\n\n')
    print(f"Number of Unique values in filtered_df_desc:{len(filtered_df_desc['Job Title'].unique())}\n\n")
    
    if len(filtered_df_desc)==len(filtered_df):
        print('It is nearly 100 % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
    else:
        percent=len(filtered_df_desc)/len(filtered_df)*100
        print(f'It is nearly {percent} % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
        
    defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
    defferences1=[] # List of titles that are not cleared as IT and Tech Job due to abnoramal desc
    defferences2=[] # List of titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc
    for value in filtered_df['Job Title'].unique():
        if value not in filtered_df_desc["Job Title"].unique():
            defferences.append(value)
            if filtered_df[filtered_df['Job Title']==value]['Job Desception'].isnull().sum()==1:
               defferences1.append(value)
            elif len(str(filtered_df[filtered_df['Job Title']==value]['Job Desception']))<64:
               defferences1.append(value)
            else:
                defferences2.append(value)
                
            
   
    print(f'list of {len(defferences)} job titles which present in filtered_df_title but not present in filtered_df_desc:\n{defferences}\n\n')
    print(f'List of {len(defferences1)} titles that are not cleared as IT and Tech Job due to abnoramal desc:\n{defferences1}\n\n')
    print(f'List of  {len(defferences2)} titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:\n{defferences2}\n\n')

In [221]:
def filter_desc(filtered_df_title,n_abnormal_desc):
    it_keywords=['computer','Computer','information technology','Information Technology','IT','software',
             'Software','network','Network','cybersecurity','Cybersecurity','developer',
             'Developer','programming','Programming','virtual','Virtual','Data','data','Digital','digital','AI','web']
    IT_jobs_IDs=[]
    n_IT_jobs=0
    loc=0
    for job_desc in filtered_df_title['Job Desception'].iloc[:]:
        flag=0
        for keyword in it_keywords:
            try:
                if keyword in job_desc:
                    flag=1
            except TypeError:
            #print('null value')
                pass
        if flag==1:
            n_IT_jobs=n_IT_jobs+1
            IT_jobs_IDs.append(filtered_df_title['Job ID'].iloc[loc])
            # filtered_df.iloc[5]['Job ID'] and filtered_df['Job ID'].iloc[5] are similar
        
        loc=loc+1
    
    n_IT_jobs
    len(IT_jobs_IDs)
    filtered_df_desc=filtered_df_title[filtered_df_title['Job ID'].isin(IT_jobs_IDs)]
    
    print(f'length of filtered_df_desc:{len(filtered_df_desc)}\n\n')
    print(f'Unique values in filtered_df_desc:\n{filtered_df_desc["Job Title"].unique()}\n\n')
    print(f"Number of Unique values in filtered_df_desc:{len(filtered_df_desc['Job Title'].unique())}\n\n")
    
    if len(filtered_df_desc)+n_abnormal_desc==len(filtered_df_title):
        print('It is nearly 100 % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
    else:
        percent=(len(filtered_df_desc)+n_abnormal_desc)/len(filtered_df_title)*100
        print(f'It is nearly {percent} % varified by Jobs desc that It belongs to IT and Tech Jobs\n\n')
        
    defferences=[] # this is list of job titles present in filtered_df_title but not in filtered_df_desc
    defferences1=[] # List of titles that are not cleared as IT and Tech Job due to abnoramal desc
    defferences2=[] # List of titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc
    for value in filtered_df_title['Job Title'].unique():
        if value not in filtered_df_desc["Job Title"].unique():
            defferences.append(value)
            if filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception'].isnull().sum()==1:
               defferences1.append(value)
            elif len(str(filtered_df_title[filtered_df_title['Job Title']==value]['Job Desception']))<64:
               defferences1.append(value)
            else:
                defferences2.append(value)
                
            
   
    print(f'list of {len(defferences)} job titles which present in filtered_df_title but not present in filtered_df_desc:\n{defferences}\n\n')
    print(f'List of {len(defferences1)} titles that are not cleared as IT and Tech Job due to abnoramal desc:\n{defferences1}\n\n')
    print(f'List of  {len(defferences2)} titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:\n{defferences2}\n\n')

In [222]:
def filter_keyword(it_tech_pattern,df_3,case):
    filtered_df_title = df_3[df_3['Job Title'].str.contains(it_tech_pattern, case)]
    print(f'length of filtered_df_title:{len(filtered_df_title)}\n\n')
    print(f'Unique values in filtered_df_title:\n{filtered_df_title["Job Title"].unique()}\n\n')
    print(f'Number of Unique values in filtered_df_title:{len(filtered_df_title["Job Title"].unique())}\n\n')
    filtered_df_title['Job Desception'].isnull().sum()
    count_of_un_complete_desc=0
    for i in range(0,len(filtered_df_title)):
        try:
            if(len(filtered_df_title.iloc[i]['Job Desception'])<20):
                # print(df.iloc[i])
                count_of_un_complete_desc=count_of_un_complete_desc+1
        except TypeError:
            pass
            # print('non value')
    if count_of_un_complete_desc==0:
        print("Not Found any uncomplete job descreption")
    n_abnormal_desc=count_of_un_complete_desc+filtered_df_title['Job Desception'].isnull().sum()
    print(f"count of_un_complete_desc in filtered_df_title:{count_of_un_complete_desc}")
    print(f"count of Null desc in filtered_df_title:{filtered_df_title['Job Desception'].isnull().sum()}")
    print(f"count of abonormal desc in filtered_df_title:{n_abnormal_desc}\n\n")
    filter_desc(filtered_df_title,n_abnormal_desc)
    
    # return filtered_df_title

### Analyzing IT keyword

In [223]:
it_tech_pattern = 'IT'
case=True
filter_keyword(it_tech_pattern,df_3,case)

length of filtered_df_title:27


Unique values in filtered_df_title:
['IT Jobs' 'SEO Executive (ON-SITE)' 'Senior Associate - IT Auditor'
 'Team Lead IT Software Development (m/f/d)'
 'IT Data Migration Specialist (m/f/d) - 100% remote' 'Director IT'
 'Manager Customer Facing IT' 'IT Sales Executive'
 'Senior Full-stack Java / Angular Developer - +10 years of IT experience - Full remote - Contractor in USD'
 'IT Support Coordinator Intern' 'IT & Network Administrator'
 'Assistant Manager IT' 'Project Manager - IT Services'
 'Executive IT Infrastructure' 'Senior Executive IT Infrastructure'
 'Manager IT BP - Digital Channels' 'Assistant Manager IT Infrastructure'
 'IT Manager - Data Engineer' 'Assistant Manager IT (Microsoft Dynamics)'
 'IT Executive' 'IT Project Manager' 'Chief Manager - IT Risk']


Number of Unique values in filtered_df_title:22


count of_un_complete_desc in filtered_df_title:1
count of Null desc in filtered_df_title:2
count of abonormal desc in filtered_df_title:3


length of filtered_df_desc:24


Unique values in filtered_df_desc:
['IT Jobs' 'SEO Executive (ON-SITE)' 'Senior Associate - IT Auditor'
 'Team Lead IT Software Development (m/f/d)'
 'IT Data Migration Specialist (m/f/d) - 100% remote' 'Director IT'
 'Manager Customer Facing IT' 'IT Support Coordinator Intern'
 'IT & Network Administrator' 'Assistant Manager IT'
 'Project Manager - IT Services' 'Executive IT Infrastructure'
 'Senior Executive IT Infrastructure' 'Manager IT BP - Digital Channels'
 'Assistant Manager IT Infrastructure' 'IT Manager - Data Engineer'
 'Senior Full-stack Java / Angular Developer - +10 years of IT experience - Full remote - Contractor in USD'
 'Assistant Manager IT (Microsoft Dynamics)' 'IT Executive'
 'Chief Manager - IT Risk']


Number of Unique values in filtered_df_desc:20


It is nearly 100 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 2 job titles which present in filtered_df_title but not present in filtered_df_desc:
['IT Sales Executive', 'IT Project Manager']


List of 2 titles that are not cleared as IT and Tech Job due to abnoramal desc:
['IT Sales Executive', 'IT Project Manager']


List of  0 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
[]

***there are many jobs in which it is cleared as IT and Tech Jobs from job titles As these are not cleared from jobs descriptions may be due to not having desc***

***count of abonormal desc in filtered_df_title:17 but List of 84 titles that are not cleared as IT and Tech Job due to abnoramal desc why*** 
***problem arised due to*** 
len(str(filtered_df_title[filtered_df_title['Job Title']=='IT Project Manager']['Job Desception']))<64:

In [224]:
# filtered_df_title[filtered_df_title['Job Title']=='Digital Marketing Strategist and Planner']['Job Desception']
# filtered_df_title[filtered_df_title['Job Title']=='Digital Marketing Strategist and Planner'].index
# # filtered_df_title[filtered_df_title['Job Title']=='Digital Marketing Strategist and Planner'].index.key()
# filtered_df_title[filtered_df_title['Job Title']=='Digital Marketing Strategist and Planner'].index.item()
# loc=filtered_df_title[filtered_df_title['Job Title']=='Digital Marketing Strategist and Planner'].index.item()
# filtered_df_title.iloc[93]

In [225]:
# 290+84

In [226]:
# 514-374

### Analyzing tech keyword

In [256]:
it_tech_pattern = 'Tech'
case=False # 145 for True and 150 for Flase
filter_keyword(it_tech_pattern,df_3,case)

length of filtered_df_title:150


Unique values in filtered_df_title:
['Technical Business Analyst' 'Fintech B2B Marketing Executive'
 'Senior Technical Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'Technical Recruiter' 'ERP Technical Support' 'Technical Content Writer'
 'ASSISTANT MANAGER COMPLIANCE- INFORMATION TECHNOLOGY' 'Technical Writer'
 'Dynamics 365 F&O Technical Consultant'
 'Technical Customer Support Specialist' 'Technical Project Manager'
 'Cloud Technical Specialist' 'Technical Project Manager/ Scrum Master'
 'Engineering Technician' 'Radiologic Technologist'
 'Technical Lead - .NET' 'Senior Technical Project Manager'
 'Technical Advisor for Development of Women Entrepreneurship Policy - Islamabad'
 'Technical Product Manager'
 'Senior Technical Support Analyst, Skyvera (Remote) - $30,000/year USD'
 'Technical Advisor Environmental Health - Asia'
 'Technical Sales Representative'
 'Head of Technology and Mechanization - Agri'
 'Technical Team Lead, Trilogy (Remote) - $100,000/year USD'
 'Technical Lead .NET' 'Assistant Manager Technical Sales'
 'Technical Lead' 'Cardiac Catheterization Laboratory Technologist'
 'Sr Associate Technical Client Support' 'Site Technician'
 'Talent Acquisition Specialist (Technical Recruiter)'
 'Technical Team Lead' 'Project Manager Technical Lead'
 'Technical Delivery Specialist – Microsoft Dynamics 365'
 'Senior Lay Equipment Technician' 'Technical Lead ML DevOps Engineer'
 'Associate Technical Client Support' 'Tier 1 Support Technician'
 'Chief Technology Officer' 'Technical Support Specialist'
 'Technical Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'Technical VFX Artist' 'Solar Installation Technician (Project Based)'
 'Endoscopy Technician' 'Lead Technical Support Engineer'
 'Lead Generation Manager, Technology & Data Strategy'
 'Technical Project Manager (Evening Shift)' 'DM Technical Performance'
 'Technology Consulting- SAP- EAM- Rapid Innovation'
 'Lead Generation Intern ( Technical )' 'Technical Manager'
 'Technical Support - Shopify' 'Information Technology Business Partner'
 'Tech Trainer' 'Information Technology Functional Partner'
 'Information Technology Help Desk Manager'
 'Senior Technical Content Writer' 'Migration Technical Lead'
 'Pakistan CSA: Agricultural Technology Special'
 'Technical SEO Specialist' 'Laboratory Technician' 'Technician'
 'Plant Technician' 'Assistant Manager Technical Services'
 'Solar Inverter Repair Technician' 'Fortify Lead Technical Consultant'
 'Information Technology Intern' 'Technical Doc Writer'
 'Technical Support Analyst, Skyvera (Remote) - $20,000/year USD'
 'Technical Support Representative, Skyvera (Remote) - $15,000/year USD'
 'Technical Product Owner, Trilogy (Remote) - $100,000/year USD'
 'Information Technology Sales Executive'
 'Information Technology Project Manager' 'Fintech Developer'
 'Food Technologist' 'MS Dynamics 365 F&O - Technical Architect'
 'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)'
 'Information Technology Support Engineer'
 'Technical Application Specialist - Molecular Diagnosis'
 'Technical Lead Frontend - UI'
 'Project Manager( FinTech) ( Forex Trading)'
 'Fintech Products B2B Marketer (Freelance)' 'Fullstack Tech Lead'
 'Technical Support Engineer, Developer Support'
 'Information Technology Business Analyst' 'Technical Support Engineer'
 'Ariba Techno/Functional Analyst'
 'Microsoft Dynamics 365 Technical Support, Power Platform'
 'Technical Associate Program 2023 - Excellent Opportunity for Fresh Graduates in Pakistan'
 'Trainee Technical Product Support Engineer'
 'Information Technology Coordinator - Sales'
 'Technical Support Executive' 'Bilingual (French) Support Technician'
 'Technical Support Specialist, Skyvera (Remote) - $15,000/year USD'
 'D365 Technical Consultant' 'Technical Sales Engineer'
 'Commodities Technical Analyst'
 'Technical Specialist, (Peshawar), Pakistan'
 'Technical Lead - Software & AI' 'Technical Proposal Writer'
 'Oracle Fusion Technical Consultant' 'Non Technical Project Manager'
 'Technical Support Engineer (Solar Inverter + EVCS + Portable Power Station）'
 'Information Technology Security Manager' 'Senior Technical Writer'
 'Microsoft Dynamics Consultant (Technical)'
 'Strategic Business Unit – Technical & Business Resources'
 'Electronic Technician (Sukkur, Pakistan)'
 'Technical Product Manager (OTE $80,000/year USD), Sparkrock']


Number of Unique values in filtered_df_title:109


count of_un_complete_desc in filtered_df_title:1
count of Null desc in filtered_df_title:2
count of abonormal desc in filtered_df_title:3


length of filtered_df_desc:128


Unique values in filtered_df_desc:
['Technical Business Analyst'
 'Senior Technical Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'Technical Recruiter' 'ERP Technical Support' 'Technical Content Writer'
 'ASSISTANT MANAGER COMPLIANCE- INFORMATION TECHNOLOGY' 'Technical Writer'
 'Dynamics 365 F&O Technical Consultant'
 'Technical Customer Support Specialist' 'Technical Project Manager'
 'Cloud Technical Specialist' 'Technical Lead - .NET'
 'Senior Technical Project Manager'
 'Technical Advisor for Development of Women Entrepreneurship Policy - Islamabad'
 'Technical Product Manager'
 'Senior Technical Support Analyst, Skyvera (Remote) - $30,000/year USD'
 'Technical Advisor Environmental Health - Asia'
 'Technical Sales Representative'
 'Head of Technology and Mechanization - Agri'
 'Technical Team Lead, Trilogy (Remote) - $100,000/year USD'
 'Technical Lead .NET' 'Technical Lead'
 'Sr Associate Technical Client Support'
 'Talent Acquisition Specialist (Technical Recruiter)'
 'Technical Team Lead' 'Project Manager Technical Lead'
 'Senior Lay Equipment Technician' 'Technical Lead ML DevOps Engineer'
 'Associate Technical Client Support' 'Tier 1 Support Technician'
 'Engineering Technician' 'Chief Technology Officer'
 'Technical Support Specialist'
 'Technical Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'Technical VFX Artist' 'Lead Technical Support Engineer'
 'Lead Generation Manager, Technology & Data Strategy'
 'Technical Project Manager (Evening Shift)' 'DM Technical Performance'
 'Technology Consulting- SAP- EAM- Rapid Innovation'
 'Lead Generation Intern ( Technical )' 'Technical Support - Shopify'
 'Information Technology Business Partner' 'Tech Trainer'
 'Information Technology Help Desk Manager'
 'Senior Technical Content Writer' 'Migration Technical Lead'
 'Pakistan CSA: Agricultural Technology Special'
 'Technical SEO Specialist' 'Laboratory Technician' 'Technician'
 'Plant Technician' 'Assistant Manager Technical Services'
 'Fortify Lead Technical Consultant' 'Information Technology Intern'
 'Technical Doc Writer'
 'Technical Support Analyst, Skyvera (Remote) - $20,000/year USD'
 'Technical Support Representative, Skyvera (Remote) - $15,000/year USD'
 'Technical Product Owner, Trilogy (Remote) - $100,000/year USD'
 'Information Technology Sales Executive'
 'Information Technology Project Manager' 'Fintech Developer'
 'MS Dynamics 365 F&O - Technical Architect'
 'Information Technology Support Engineer'
 'Technical Application Specialist - Molecular Diagnosis'
 'Technical Lead Frontend - UI'
 'Project Manager( FinTech) ( Forex Trading)' 'Fullstack Tech Lead'
 'Technical Support Engineer, Developer Support'
 'Information Technology Business Analyst' 'Technical Support Engineer'
 'Ariba Techno/Functional Analyst'
 'Microsoft Dynamics 365 Technical Support, Power Platform'
 'Trainee Technical Product Support Engineer'
 'Information Technology Coordinator - Sales'
 'Technical Support Executive' 'Bilingual (French) Support Technician'
 'Technical Support Specialist, Skyvera (Remote) - $15,000/year USD'
 'D365 Technical Consultant' 'Technical Sales Engineer'
 'Commodities Technical Analyst'
 'Technical Specialist, (Peshawar), Pakistan'
 'Technical Lead - Software & AI' 'Oracle Fusion Technical Consultant'
 'Non Technical Project Manager'
 'Technical Support Engineer (Solar Inverter + EVCS + Portable Power Station）'
 'Information Technology Security Manager' 'Senior Technical Writer'
 'Microsoft Dynamics Consultant (Technical)'
 'Strategic Business Unit – Technical & Business Resources'
 'Electronic Technician (Sukkur, Pakistan)'
 'Technical Product Manager (OTE $80,000/year USD), Sparkrock']


Number of Unique values in filtered_df_desc:92


It is nearly 87.33333333333333 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 17 job titles which present in filtered_df_title but not present in filtered_df_desc:
['Fintech B2B Marketing Executive', 'Technical Project Manager/ Scrum Master', 'Radiologic Technologist', 'Assistant Manager Technical Sales', 'Cardiac Catheterization Laboratory Technologist', 'Site Technician', 'Technical Delivery Specialist – Microsoft Dynamics 365', 'Solar Installation Technician (Project Based)', 'Endoscopy Technician', 'Technical Manager', 'Information Technology Functional Partner', 'Solar Inverter Repair Technician', 'Food Technologist', 'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)', 'Fintech Products B2B Marketer (Freelance)', 'Technical Associate Program 2023 - Excellent Opportunity for Fresh Graduates in Pakistan', 'Technical Proposal Writer']


List of 1 titles that are not cleared as IT and Tech Job due to abnoramal desc:
['Technical Associate Program 2023 - Excellent Opportunity for Fresh Graduates in Pakistan']


List of  16 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['Fintech B2B Marketing Executive', 'Technical Project Manager/ Scrum Master', 'Radiologic Technologist', 'Assistant Manager Technical Sales', 'Cardiac Catheterization Laboratory Technologist', 'Site Technician', 'Technical Delivery Specialist – Microsoft Dynamics 365', 'Solar Installation Technician (Project Based)', 'Endoscopy Technician', 'Technical Manager', 'Information Technology Functional Partner', 'Solar Inverter Repair Technician', 'Food Technologist', 'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)', 'Fintech Products B2B Marketer (Freelance)', 'Technical Proposal Writer']

Why these jobs are not in IT by desc?:

'Technical Project Manager/ Scrum Master':
Agile,testing:testing can be in non IT jobs like 'Chemist (Third Party Contract)','Food Technologist','Product Owner',project 
'Assistant Manager Technical Sales' Non tech job:non IT job
'Information Technology Functional Partner':BS(CS),SAP
'Technical Delivery Specialist – Microsoft Dynamics 365'
'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)'
'Fintech Products B2B Marketer (Freelance)'
'Technical Proposal Writer'

In [228]:
df_3[df_3['Job Title']=='Technical Delivery Specialist – Microsoft Dynamics 365']['Job Desception']
df_3.loc[2115]
df_3.loc[2115]['Job Desception']

'About the job\n            \n\n \nKey Responsibilities: Manage and oversee the end-to-end project delivery lifecycle, ensuring that deliverables are completed within time, scope, and budget constraints.Collaborate closely with cross-functional teams, including , Technical and Functional Consultants and other Stakeholders to ensure seamless project execution.Drive continuous improvement initiatives within the delivery team, identifying areas of improvement in processes, tools, and methodologies.Resolve technical and process-related challenges, mitigating project risks, and managing stakeholder expectations.Ensure that all project documentation, including specifications, designs, and testing artifacts, are of the highest quality and maintained.Provide regular project status updates to senior leadership and stakeholders, including budget, progress, risks, and dependencies.Foster a culture of innovation, collaboration, and customer-centricity within the team.\n Education: BS degreeExperience: 8-10 years or moreSalary: Market CompetitiveBenefits:> Health Insurance Coverage> Loan Facility> Bi-Annual Increment> Quarterly Bonus> Performance-based Promotions> Provident Fund> Paid Leaves> Professional development opportunities> Free of cost training and certifications Interested candidates can Apply/Refer at\xa0zehra.hussain@kaispe.com #dynamics365\xa0#microsoftdynamics365\xa0#hiringnow\xa0#karachijobs\xa0#technicaljobs\xa0#technicaldeliveryconsultant'

In [229]:
'project' in df_3.loc[643]['Job Desception']

True

In [230]:
'testing' in df_3.loc[643]['Job Desception']

True

In [231]:
'Agile' in df_3.loc[643]['Job Desception']

True

In [241]:
it_tech_pattern = 'Agile'
case=False 
filter_desc_by_one_keyword(df_3,it_tech_pattern,case)

length of filtered_df_desc:329


Unique values in filtered_df_desc:
['Associate Engineer' 'Dotnet+React Developer'
 'Technical Business Analyst' 'Full Stack Developer'
 'Business Development Executive' 'Software Quality Assurance Engineer'
 'Senior Software Engineer' 'Microsoft Dynamics Consultant'
 'Python/Django Developer' 'TV App Developer'
 'Project Manager (Agile & Delivery Management)' 'Dotnet Developer'
 'Software Engineer' 'Expert Internal Audit' 'Scala Developer'
 'Senior Python Developer' 'Technical Project Manager'
 'Software Development Engineer in Test (SDET)' 'UX Designer'
 'Full Stack Engineer - AI expert'
 'Software Engineer - Marketing Platform' 'Java Consultant'
 '.Net Developer - C# - MVC' 'Senior QA Engineer'
 'Microsoft Dynamics 365 CRM Developer'
 'Quality Assurance Automation Engineer' 'Release Management Engineer'
 'Senior Software Development Project Manager' 'Senior Project Manager'
 'Full Stack Developer (.Net & Angular)' 'mid Lavel Laravel Developer'
 'Full Stack Engineer' 'Software Architect Lead Developer'
 'Senior Full Stack Web Developer (PHP Laravel, VueJS, NodeJS)'
 'Unity Developer' 'Laravel Developer'
 'Principal Software Engineer Full Stack PHP'
 'Senior Java Software Engineer' 'Angular developer'
 'Senior Full Stack Engineer' 'Product Owner'
 'Senior Business Analyst (Pre-Sales)'
 'Senior Franchise Manager - Karachi Based'
 'Full Stack Dotnet Developer with Angular'
 'Full Stack Developer with 1.5 Years of Experience'
 'Digital Treatment Planning - Trainer' 'Dot Net Core Developer'
 'Flutter Developer' 'Voice User Interface (VUI) Designer'
 'Technical Lead .NET' 'Senior MERN Stack Developer | Team Lead'
 'Technical Lead' 'Lead Quality Assurance Engineer (Semi-Automation)'
 'Senior API Developer' 'Senior Dotnet Developer'
 'Senior MEAN/MERN Developer' 'Data Activation & Delivery Manager'
 'Research Executive, Customer Success' 'Senior MicroStrategy Consultant'
 'Software Engineer II- Android'
 'Senior Manager Data & Analytics Activations'
 'Manager Frontend App Development' 'Digital Research Manager'
 'C++ Software Engineer II' 'Senior Software Developer' 'SQA Engineer'
 'Senior C++ Software Engineer' 'Project Coordinator' 'Android Developer'
 'Software Development Team Leader' 'Senior Java Engineer (Backend)'
 'Senior React Js Developer' 'Associate Infraops Engineer'
 'Finance Enterprise Partner' 'PHP/ Wordpress Developer'
 'ODOO Software Developer' 'Software Engineer - iOS'
 'Ingénieur Système Expert Windows H/F' 'Senior SQA Engineer - Automation'
 'Senior Data Engineer' 'Operations Manager'
 'Principal Software Quality Assurance Engineer' 'SQA Engineer - Mobile'
 'Front End Shopify Developer'
 'Experienced Full-Stack Developer with Web Development Experience (Remote Position)'
 'Senior Business Analyst' 'Senior Software Engineer IV'
 'CONCEPTEUR FORMATION H/F' 'Senior Software Engineer - Flutter'
 'Business Analyst (telecommunication)' 'Project Manager'
 'Senior SQA Engineer' 'SQA' 'iOS Developer'
 'Senior .Net Developer (Integrations)' 'Senior DevOps Engineer'
 'Celonis Process Mining Value Architec - Pakistan'
 'Senior Salesforce Developer' 'Business Analyst (Night Shift)'
 'Technical Project Manager (Evening Shift)' 'Engineering Manager'
 'UI/UX Designer' 'Senior Software Engineer - Ruby on Rails'
 'React-Native Developer' 'Senior Full Stack Developer'
 'Agile Product Development Analyst'
 'Cross-Platform Mobile Developers M5164' 'DevOps Manager'
 'Cross-Platform Mobile Developer M5164'
 'Internship Program - Angular frontend developer'
 'Quality Assurance Engineer' 'Manager Customer Facing IT'
 'Software Project Manager' 'Product Marketing & Growth Manager/Lead'
 'WPF Developer' 'Senior Data Operations Engineer'
 'Solutions Architect (Karachi, Pakistan)' 'Solutions Architect'
 'Sr.SQA Engineer' 'Software Architect' 'Frontend Developer'
 'Angular Developer' 'Back End Developer' 'Development Team Lead'
 'SQA Engineer (Team Lead)' 'C# .NET Software Engineer'
 'Cross Platform Mobile Developer'
 'Senior Mobile and AI Application Developer'
 'Head of Software Engineering (Python)' 'Senior Software Engineer (.Net)'
 'Senior .Net MAUI /Xamarin developer' 'Billing Project Executive'
 'Lead Support Engineer'
 'Expression of Interest - Consumer Foresights Manager'
 'Customer Solution Expert' 'Senior Ruby On Rails Engineer (ROR)'
 'Windows Application Architect' 'RCM Specialist' 'Maintenance Engineer'
 'QA Engineer' 'Maintenance Officer' 'Sap Materials Management Consultant'
 'DevOps Engineer' 'Software Engineering Manager'
 'Mulesoft Consultant (Part Time)' 'MERN Stack Developer'
 'Plant Technician' 'Node Js Developer' 'Node Js. Developer'
 'ASP.NET Senior Lead Developer' 'Senior Frontend Developer'
 'Senior Salesforce Developer - Architecture' 'Senior Full-Stack Engineer'
 'Sharepoint Consultant' 'Business Analyst I' 'Data Analyst'
 'Data Engineer' 'QA Engineer - Manual' 'Technical Doc Writer'
 'Expression of Interest - Brand Development Executive' 'Content Editor'
 'Support Specialist' 'Expression of Interest - Brand Development Manager'
 'Software Engineer III-Django' 'RPA UI Path Engineer'
 'Salesforce Developer' 'QA Engineer - Mobile'
 'Software Architect - Python' 'Software Quality Assurance Manager'
 'Mern Stack Developer' 'AI - Full Stack Engineer'
 'Principal Software Engineer' 'Sr. SQAE Automation'
 'Business Analyst I (Salesforce)' 'Android Development internship'
 'Technical Lead Frontend - UI'
 'Salesforce Support Associate (Contractual Role)'
 'Senior Backend Developer' 'Java Developer (Backend)'
 'Senior Software Engineer (Fullstack)'
 'Senior Software Quality Assurance Engineer' 'SEO Executive'
 'Project Manager( FinTech) ( Forex Trading)' 'Fullstack Tech Lead'
 'Senior Devops Engineer' 'Full Stack Lead Software Engineer'
 'Senior .Net Core/Angular Developer' 'Senior Nodejs Developer'
 'SQA Analyst' 'MicroStrategy Developer'
 'Software Quality Assurance (Manual) - Pakistan'
 'Senior Dynamics 365 CRM Solution Architect'
 'Senior Software Engineer - Java Spring Boot (4-7 years)'
 'IT Manager - Data Engineer'
 'Test Automation Engineer (Relocation to Malaysia)' 'Marketo Developer'
 'Associate Product Manager' 'Supply Network Executive'
 'Associate Developer, Java' 'Value Stream Lead (Jamshoro)'
 'Business Development Associate' 'Senior Backend Engineer - PHP'
 'ClickUp Specialist' 'Quality Assurance Specialist'
 'PHP/Laravel Developer' 'Senior Software Engineer/Fullstack'
 'Technical Lead - Software & AI' 'Front sales Design'
 'PHP Laravel Developer' 'Nodejs Developer' 'Azure Backend Developer'
 'Senior Software Development Engineer in Test - Data Analytics'
 'BI Engineer/Looker Dashboard Developer'
 'Digital Business Analyst - Insights and Analytics'
 'Senior DevOps Engineer (AWS)' 'Quality Assurance (QA) Specialist'
 'Senior AWS Engineer' 'Service Design Specialist'
 'Principal Software Engineer (Backend)' 'Non Technical Project Manager'
 'Django React Full Stack Developer' 'full stack developer'
 'Lead Full Stack Web Developer' 'Senior MERN Stack Developer'
 'Software Development  Manager' 'MERN STACK Developer'
 'Senior Dotnet + React Developer' 'Senior Field Marketing Manager- Japan'
 'Senior Field Marketing Manager- South Korea'
 'Senior .Net Full Stack Developer' 'Software Test Engineer'
 'Head of Digital Product & Solution'
 'Senior Software Engineer (AI/Infra)' 'Full Stack NextJS Developer'
 'Senior Dot Net Developer' 'Senior Software Engineer (Vue.js)'
 'Senior PHP Developer' 'Wordpress Developer'
 'Digital Energy Prescription Manager' 'Senior WordPress Developer'
 'Cash Management Product Manager (Mashreq Global Network Pakistan)'
 'Full Stack Engineer (Laravel + Angular)' 'Sr. SQA Automation Engineer'
 'Javascript/Angular Developer' 'Executive Assistant (Work From Home)'
 'Salesforce Solution Architect' 'Senior IOS Developer']


Number of Unique values in filtered_df_desc:247


It is nearly 97.33727810650888 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 6 job titles which present in filtered_df_title but not present in filtered_df_desc:
['Technical Project Manager/ Scrum Master', 'Business Development Intern', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Production Officer', 'Cloud Automation & Application Engineer(Team Lead)', 'Quality System Lead (Jamshoro)']


List of 0 titles that are not cleared as IT and Tech Job due to abnoramal desc:
[]


List of  6 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['Technical Project Manager/ Scrum Master', 'Business Development Intern', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Production Officer', 'Cloud Automation & Application Engineer(Team Lead)', 'Quality System Lead (Jamshoro)']

In [260]:
it_tech_pattern = 'app'
case=False 
filter_desc_by_one_keyword(df_3,it_tech_pattern,case)

length of filtered_df_desc:1990


Unique values in filtered_df_desc:
['It Management Intern' 'SQL Database Developer'
 'Business Intelligence Developer' ...
 'Engineer, Service-to-Service Fabric'
 'Technical Product Manager (OTE $80,000/year USD), Sparkrock'
 'Senior IOS Developer']


Number of Unique values in filtered_df_desc:1364


It is nearly 84.68085106382979 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 222 job titles which present in filtered_df_title but not present in filtered_df_desc:
['Customer Support Representative', 'Customer Experience Executive', 'Upwork Bidding Specialist', 'Junior Officer Agri Purchases', 'Student Leader - Chemistry', 'Business Development Representative-Australia region', 'Proofreader', 'Human Resources and Admin Executive', 'Customer Service Team Lead', 'Study Abroad Advisor', 'AM/Manager HR-Total Reward', 'Senior Business Development Officer', 'Export Operations Specialist', 'Etsy Store Manager', 'Community Manager', 'Immigration Consultant', 'Production Officer', 'Senior Customer Service Representative', 'Relationship Officer (Credit Cards Sales)', 'IELTS & PTE Trainer', 'Assistant Manager Sales/Sales Executive', 'Assistant Professor', 'Front Sales & Support (Bark & PPC)', 'Process Improvement Manager', 'Bpo specialist / Team Lead Sales', 'Sales Executive - North Region (KPK)', 'Human Resources Development Specialist', 'FDO - Front Desk Officer', 'Assistant Merchandiser/ Merchandiser', 'Real Estate Sales Agent', 'Claims Manager', 'Sales Support Coordinator', 'Senior Officer', 'Telesales Representative - Appointment Setter', 'Assistant Manager - Audit & Accounts', 'UK Accent Customer Service Representative', 'Head of Compliance-Banking Industry', 'Autocad/Solidworks Professional', 'Architectural Drafter', 'PowerBi Data Analyst', 'Supply Chain Executive', 'Sales Intern', 'Customer Service Executive', 'Front Desk Receptionist', 'Consultant/Production Manager Detergent Manufacturing Unit', 'ARM/RM - Direct Sales - Karachi', 'Computer Numerical Control Programmer', 'Associate- Project Sales', 'Associate Project Sales', 'Sales Representative (Remote Based)', 'Associate Proefssor-Pakistan- remote', 'Call Center Agent', 'Chemistry Teacher', 'Sales Consultant (Project Sales)', 'Coordinator Regulatory', 'Principal', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Senior 3D Artist', 'Import Officer', 'Logistics Operations Specialist', 'Customer Support Executive UAE', 'Business Development Executive - Export/ Local', 'Manager Sales & Business Development', 'Compliance Manager', 'Scaffolding Inspector', 'One Identity Resident Engineer', 'Fashion& Textile Design Teacher', 'Lifting Equipment Inspector', 'Game UI/UX Artist', 'Affiliate Sales (Indirect)', 'Technical Delivery Specialist – Microsoft Dynamics 365', 'Supervisory Senior- Audit', 'PhD Studentship Department of Environmental Sciences Prof. Dr. Muhammad Riaz', 'Sale Executive', 'SEO Sales Agent', 'Product Quality Associate - MEA', 'Health Representative - Rahim Yar Khan', 'FP&A Manager', 'Aspire for Unilever - AM E&I', 'Territory Manager - Peshawar', 'Legal Secretary', 'International Sales & Marketing Executive', 'Draftsman', 'Pharmacist', 'Human Resources Business Partner', 'Senior Sap Finance Control Consultant', 'Travel Organizer', '𝐂𝐚𝐦𝐩𝐮𝐬 𝐅𝐚𝐜𝐢𝐥𝐢𝐭𝐚𝐭𝐨𝐫', 'Solar Installation Technician (Project Based)', 'Management Trainee Program', 'Service Delivery Manager-P2P', 'US Trucking Shipping Coordinators', 'Accounting Manager', 'Affiliate content writer', 'AM Business Development', 'Processing Manager', 'Audit Partner', 'Experienced Freight Forwarders to Join Fast Growing Logistics Provider PK', 'Production Manager', 'External Audit Manager', 'Primary School Principal', 'News Anchor', '4 - 5 Axis CNC Milling VMC Programmer Machinist', 'Home Textiles Export Manager', 'Associate Professor - Avionics Engineering', 'Research Academic Writer', 'International Recruitment Manager- Pakistan', 'Technical Manager', 'Sales Support Specialist', 'Client Success Specialist', 'Team Management', 'Financial Advisor', 'Restaurant GRO', 'Pre-Sales CCTV Networking Expert', 'Customer Success Arabic', 'Senior Executive - Audit (Operations)', 'Experienced Freight Forwarders to Join Fast Growing Logistics Provider', 'Tourism Manager', 'Production Supervisor', 'Head of Planned Maintenance', 'Customer Relations Manager', 'Graphic Designer Trainer', 'Team Head', 'Assistant Manager Audit', 'Analyst Client Care - Contract', 'Marketing Intern', 'Energizer Business Excellence', 'Business Development Assistant', 'Senior Buyer - Indirect Procurement', 'International Student Advisor', 'Model', 'Screener (Male)', 'Carrier Onboarding / Sales Executive at a Truck Dispatching LLC!', 'Security Guard (H-209)', 'Call Center Specialist', 'Head of Risk', 'Sublimation Designer', 'Production Pharmacist', 'Sr. Accounts Executive-(H-214-01)', 'Maçon coffreur N3P2', 'Nutritionist, Child specialist', 'Counselling Mentor / Program Advisor', 'Executive Commercial & General Procurement', 'Sales pool (Fresh graduates)', 'Regional Recruitment Representative- Pakistan', 'Senior Executive/AM Business Planning Analysis', 'Regional Visibility Executive', 'Area Sales Manager, Karachi', 'Territory Sales Manager Gilgit', 'Customer Service Officer', 'Assistant Manager Sales', 'Sales Executive - Discord and Social Media (Chat Based)', 'SENIOR PROCESSING OFFICER', 'Front Ebook Sales', 'AM Real Estate Sales', 'Manager Group Financial Reporting', 'International Sales Executive (RSP Unit)', 'Sales Person', 'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)', 'Manager', 'Video Editor UGC/short ads', 'Hybrid intern', 'Talent Acquisition Partner', 'International Recruitment Manager - Islamabad, Pakistan', 'Quality System Lead (Jamshoro)', 'QS-Site', 'Research Analyst/ Academic Writer', 'Sales Engineer', 'Flutter Developer (Contractual)', 'Retail Sales Specialist', 'Finance Executive - Customer Counter', 'Proposal Engineer', 'Inside Sales Specialist', 'Creative Video Editor for Apps Promotions & Ad Campaigns.', 'Implementation Consultant', 'Inbound Sales Representative', 'Front Sales Executive (Bark)', 'Printing Head', 'Aspire for Unilever - ER Manager Foods', 'Oracle Fusion SCM Consultant', 'Senior Authorization Executive', 'Visiting Assistant Professor', 'Ebook Upseller', 'Outbound Sales Representative (US Based)', 'Off Page SEO Expert', 'Professor of Mechanical Engineering / Professor of Pharmacy/ PHD Computer Science', 'Truck Dispatching Sales Executive', 'R&D Assistant', 'Territory Manager', 'Consultant to Develop Curriculum & Deliver Training ESP - Islamabad', 'Assistant Marketing Officer', 'Sr. Territory Sales Officer, Lahore', 'Senior Physiotherapist (s)', 'Mechanical Maintenance Engineer', 'Benefit Configuration Analyst', 'Social Media Content Creator', 'Food Beverage Coordinator', 'Hebrew Linguist', 'Sales Executive (Upsell) - Design', 'English Language Instructor', 'Copywriter Onsite Johar Town', 'Admin Officer', 'Administrative Assistant', 'Boxing Instructor', 'ebook Sales', 'Business Development Executive (Quality Assurance)', 'Hospital Director', 'Senior Investment Advisor', 'Legal Manager, Pakistan(I6234)', 'PS Software Engineer', 'Senior Territory Manager', 'AVP, Head of Trade Operations', 'Assistant Manager - Quality', 'Manager ERP Functional', 'Wealth Manager', 'PPC Specialist (Night Shift)', 'Officer', 'Mobile Apps (Xamarin) - Software Developer', 'Inspection Engineer', 'Senior Medical Officer', 'Medical Officer', 'Prosecutor']


List of 0 titles that are not cleared as IT and Tech Job due to abnoramal desc:
[]


List of  222 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['Customer Support Representative', 'Customer Experience Executive', 'Upwork Bidding Specialist', 'Junior Officer Agri Purchases', 'Student Leader - Chemistry', 'Business Development Representative-Australia region', 'Proofreader', 'Human Resources and Admin Executive', 'Customer Service Team Lead', 'Study Abroad Advisor', 'AM/Manager HR-Total Reward', 'Senior Business Development Officer', 'Export Operations Specialist', 'Etsy Store Manager', 'Community Manager', 'Immigration Consultant', 'Production Officer', 'Senior Customer Service Representative', 'Relationship Officer (Credit Cards Sales)', 'IELTS & PTE Trainer', 'Assistant Manager Sales/Sales Executive', 'Assistant Professor', 'Front Sales & Support (Bark & PPC)', 'Process Improvement Manager', 'Bpo specialist / Team Lead Sales', 'Sales Executive - North Region (KPK)', 'Human Resources Development Specialist', 'FDO - Front Desk Officer', 'Assistant Merchandiser/ Merchandiser', 'Real Estate Sales Agent', 'Claims Manager', 'Sales Support Coordinator', 'Senior Officer', 'Telesales Representative - Appointment Setter', 'Assistant Manager - Audit & Accounts', 'UK Accent Customer Service Representative', 'Head of Compliance-Banking Industry', 'Autocad/Solidworks Professional', 'Architectural Drafter', 'PowerBi Data Analyst', 'Supply Chain Executive', 'Sales Intern', 'Customer Service Executive', 'Front Desk Receptionist', 'Consultant/Production Manager Detergent Manufacturing Unit', 'ARM/RM - Direct Sales - Karachi', 'Computer Numerical Control Programmer', 'Associate- Project Sales', 'Associate Project Sales', 'Sales Representative (Remote Based)', 'Associate Proefssor-Pakistan- remote', 'Call Center Agent', 'Chemistry Teacher', 'Sales Consultant (Project Sales)', 'Coordinator Regulatory', 'Principal', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Senior 3D Artist', 'Import Officer', 'Logistics Operations Specialist', 'Customer Support Executive UAE', 'Business Development Executive - Export/ Local', 'Manager Sales & Business Development', 'Compliance Manager', 'Scaffolding Inspector', 'One Identity Resident Engineer', 'Fashion& Textile Design Teacher', 'Lifting Equipment Inspector', 'Game UI/UX Artist', 'Affiliate Sales (Indirect)', 'Technical Delivery Specialist – Microsoft Dynamics 365', 'Supervisory Senior- Audit', 'PhD Studentship Department of Environmental Sciences Prof. Dr. Muhammad Riaz', 'Sale Executive', 'SEO Sales Agent', 'Product Quality Associate - MEA', 'Health Representative - Rahim Yar Khan', 'FP&A Manager', 'Aspire for Unilever - AM E&I', 'Territory Manager - Peshawar', 'Legal Secretary', 'International Sales & Marketing Executive', 'Draftsman', 'Pharmacist', 'Human Resources Business Partner', 'Senior Sap Finance Control Consultant', 'Travel Organizer', '𝐂𝐚𝐦𝐩𝐮𝐬 𝐅𝐚𝐜𝐢𝐥𝐢𝐭𝐚𝐭𝐨𝐫', 'Solar Installation Technician (Project Based)', 'Management Trainee Program', 'Service Delivery Manager-P2P', 'US Trucking Shipping Coordinators', 'Accounting Manager', 'Affiliate content writer', 'AM Business Development', 'Processing Manager', 'Audit Partner', 'Experienced Freight Forwarders to Join Fast Growing Logistics Provider PK', 'Production Manager', 'External Audit Manager', 'Primary School Principal', 'News Anchor', '4 - 5 Axis CNC Milling VMC Programmer Machinist', 'Home Textiles Export Manager', 'Associate Professor - Avionics Engineering', 'Research Academic Writer', 'International Recruitment Manager- Pakistan', 'Technical Manager', 'Sales Support Specialist', 'Client Success Specialist', 'Team Management', 'Financial Advisor', 'Restaurant GRO', 'Pre-Sales CCTV Networking Expert', 'Customer Success Arabic', 'Senior Executive - Audit (Operations)', 'Experienced Freight Forwarders to Join Fast Growing Logistics Provider', 'Tourism Manager', 'Production Supervisor', 'Head of Planned Maintenance', 'Customer Relations Manager', 'Graphic Designer Trainer', 'Team Head', 'Assistant Manager Audit', 'Analyst Client Care - Contract', 'Marketing Intern', 'Energizer Business Excellence', 'Business Development Assistant', 'Senior Buyer - Indirect Procurement', 'International Student Advisor', 'Model', 'Screener (Male)', 'Carrier Onboarding / Sales Executive at a Truck Dispatching LLC!', 'Security Guard (H-209)', 'Call Center Specialist', 'Head of Risk', 'Sublimation Designer', 'Production Pharmacist', 'Sr. Accounts Executive-(H-214-01)', 'Maçon coffreur N3P2', 'Nutritionist, Child specialist', 'Counselling Mentor / Program Advisor', 'Executive Commercial & General Procurement', 'Sales pool (Fresh graduates)', 'Regional Recruitment Representative- Pakistan', 'Senior Executive/AM Business Planning Analysis', 'Regional Visibility Executive', 'Area Sales Manager, Karachi', 'Territory Sales Manager Gilgit', 'Customer Service Officer', 'Assistant Manager Sales', 'Sales Executive - Discord and Social Media (Chat Based)', 'SENIOR PROCESSING OFFICER', 'Front Ebook Sales', 'AM Real Estate Sales', 'Manager Group Financial Reporting', 'International Sales Executive (RSP Unit)', 'Sales Person', 'Oracle Fusion HCM Consultant (Functional Consultant and Technical Consultant)', 'Manager', 'Video Editor UGC/short ads', 'Hybrid intern', 'Talent Acquisition Partner', 'International Recruitment Manager - Islamabad, Pakistan', 'Quality System Lead (Jamshoro)', 'QS-Site', 'Research Analyst/ Academic Writer', 'Sales Engineer', 'Flutter Developer (Contractual)', 'Retail Sales Specialist', 'Finance Executive - Customer Counter', 'Proposal Engineer', 'Inside Sales Specialist', 'Creative Video Editor for Apps Promotions & Ad Campaigns.', 'Implementation Consultant', 'Inbound Sales Representative', 'Front Sales Executive (Bark)', 'Printing Head', 'Aspire for Unilever - ER Manager Foods', 'Oracle Fusion SCM Consultant', 'Senior Authorization Executive', 'Visiting Assistant Professor', 'Ebook Upseller', 'Outbound Sales Representative (US Based)', 'Off Page SEO Expert', 'Professor of Mechanical Engineering / Professor of Pharmacy/ PHD Computer Science', 'Truck Dispatching Sales Executive', 'R&D Assistant', 'Territory Manager', 'Consultant to Develop Curriculum & Deliver Training ESP - Islamabad', 'Assistant Marketing Officer', 'Sr. Territory Sales Officer, Lahore', 'Senior Physiotherapist (s)', 'Mechanical Maintenance Engineer', 'Benefit Configuration Analyst', 'Social Media Content Creator', 'Food Beverage Coordinator', 'Hebrew Linguist', 'Sales Executive (Upsell) - Design', 'English Language Instructor', 'Copywriter Onsite Johar Town', 'Admin Officer', 'Administrative Assistant', 'Boxing Instructor', 'ebook Sales', 'Business Development Executive (Quality Assurance)', 'Hospital Director', 'Senior Investment Advisor', 'Legal Manager, Pakistan(I6234)', 'PS Software Engineer', 'Senior Territory Manager', 'AVP, Head of Trade Operations', 'Assistant Manager - Quality', 'Manager ERP Functional', 'Wealth Manager', 'PPC Specialist (Night Shift)', 'Officer', 'Mobile Apps (Xamarin) - Software Developer', 'Inspection Engineer', 'Senior Medical Officer', 'Medical Officer', 'Prosecutor']

['Technical Project Manager/ Scrum Master', 'Business Development Intern', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Production Officer', 'Cloud Automation & Application Engineer(Team Lead)', 'Quality System Lead (Jamshoro)']
Microsoft Office

In [253]:
df_3[df_3['Job Title']=='Production Officer']['Job Desception']
# df_3.loc[1531]
# df_3.loc[2115]['Job Desception']

376     About the job\n            \n\n \nSite Name: P...
1852    About the job\n            \n\n \nWhy Patients...
Name: Job Desception, dtype: object

In [255]:
# df_4=df_3.dropna(subset=['Job Desception'])
# filtered_df= df_4[df_4['Job Desception'].str.contains(it_tech_pattern, case)]
# filtered_df
# filtered_df[filtered_df['Job Title']=='Production Officer']['Job Desception']
# # df_3.loc[903]
# df_3.loc[1852 ]['Job Desception']

"About the job\n            \n\n \nWhy Patients Need YouOur breakthroughs would not make it to the hands of patients without our pharmaceutical manufacturing team. We rely on a team of dedicated and agile members, who understand the importance and impact of their role in Pfizer’s mission. Patients need colleagues like you who take pride in their work and always look to improve outcomes. You will help to ensure that patients and physicians have the medicines they need, when they need them.What You Will AchieveYour expertise in the manufacturing domain will help you in communicating and directing the activities of employees in the production areas in an effective manner. You will be entrusted with addressing deviations to process problems in the production areas and manage timely equipment maintenance. You will ensure current Good Manufacturing Practices compliance, meet area performance measures, and promote employee training.As an associate, your focus on the job will contribute in achieving project tasks and goals. Through your domain knowledge and commitment, you will create a collaborative teaming environment for your colleagues.It is your hard work and focus that will help in making Pfizer ready to achieve new milestones and help patients across the globe.How You Will Achieve It Contribute to completion of project milestones and organize own work to meet project task deadlines. Respond to safety related items and assures corrective actions are taken when necessary. Responsible for identifying and implementing efficiency, safety, quality and cost improvements on equipment and processes. Promote cGMP (current Good Manufacturing Practices) compliance within the workplace by following site cGMP procedures. Assures standard operating procedures are updated and adhered. Develop appropriate metrics and action plans to ensure customer/business needs are met. Manage supervision of inspection, reconciliation or dispensing and receivals of components. Apply project management skills to lead and participate in cross-functional teams to deliver objectives on time. \nQualificationsMust-Have Bachelor's Degree in PharmaceuticalsEffective verbal and written communication skillsDemonstrated proficiency in MS Office programs, including MS Project or equivalent\nNice-to-Have Experience in pharma industry\nPfizer is an equal opportunity employer and complies with all applicable equal employment opportunity legislation in each jurisdiction in which it operates.Manufacturing"

### Analyzing developer keyword

In [258]:
it_tech_pattern = 'developer'
case=False # 21 for True and 533 for Flase
filter_keyword(it_tech_pattern,df_3,case)

length of filtered_df_title:533


Unique values in filtered_df_title:
['SQL Database Developer' 'Business Intelligence Developer'
 'Web Developer - Internship' 'Dotnet+React Developer'
 'Artificial Intelligence Developer' 'Junior Business Developer'
 'Jr Business Developer (Upwork)' 'Full Stack Developer'
 'Python Developer with Data Science Focus' 'Odoo Developer'
 'Web Developer' 'SOFTWARE DEVELOPER' 'Salesforce Developer'
 'SEO Developer' 'Python/Django Developer' 'Application Developer'
 'Back End Developer' 'Shopify Developer' 'Junior Dotnet Developer'
 'Associate MERN Stack Developer' 'TV App Developer' 'Wordpress Developer'
 'Dotnet Developer' 'PHP Developer Required'
 'AI-Augmented Software Developer, Trilogy (Remote) - $200,000/year USD'
 'Shopify App Developer' 'Full Stack Dotnet Developer'
 'Lead Web Developer' 'Senior Web Developer' 'Scala Developer'
 'Senior Python Developer' 'HubSpot Developer' 'MERN Stack Developer'
 'Node.JS Developer' 'Software Developer'
 'Full stack Developer (Mid-Level)' '.Net Developer - C# - MVC'
 'Microsoft Dynamics 365 CRM Developer' 'Trainee iOS Developer'
 'Mern Stack Developer'
 'MERN Stack Developer - ReactJS, NodeJS, Apollo, Graphql & MongoDB'
 'Full Stack Developer (.Net & Angular)' 'Game Developer'
 'full stack developer' 'Javascript Developer'
 'mid Lavel Laravel Developer' 'Android Developer'
 'MERN and React Native Developer' 'Software Architect Lead Developer'
 'Node.Js Developer' 'Senior .NET Developer/Lead'
 'Full Stack PHP developer' 'Senior Mern Stack Developer'
 'Senior Full Stack Web Developer (PHP Laravel, VueJS, NodeJS)'
 'Unity Developer' 'WordPress backend developer'
 'Mobile Application Developer' 'Laravel Developer' 'Angular Developer'
 'iOS Developer' 'Senior MERN STACK Developer'
 'Frontend Vue j.s developer' 'Sr Flutter Developers'
 'Lead Java Developer' 'Senior .net core API developer'
 'Senior MERN Stack Developer' 'Angular developer'
 'Unity  Android Mobile Game Developer' 'Junior iOS Developer'
 'Senior Node JS Developer' 'Lead ReactJS Developer - Web TV Application'
 'Senior React Native Developer' 'Senior PHP Developer'
 'Senior Fullstack Elixir Developer' 'Sr. React Native developer'
 'Sr. Angular Developer' 'Senior Angular Developer'
 'Junior Backend Developer (Python)' 'Frontend Developer'
 'Python Developer'
 'AI-Augmented Software Developer, Skyvera (Remote) - $200,000/year USD'
 'User Interface Developer' 'Front-End Developer' 'flutter Developer'
 'Shopify Back End Developer' 'Full Stack Dotnet Developer with Angular'
 'International Business Trade Developer- Pakistan/Bangladesh'
 'ReactJS Developer' 'Full Stack Developer with 1.5 Years of Experience'
 'Software/Application Developer' 'PHP Developer'
 'Back End Developer, Trilogy (Remote) - $100,000/year USD'
 'Magento Developer' 'Flutter Application Developer'
 'Dot Net Core Developer' 'Flutter Developer' 'PHP Backend Developer'
 'Senior MERN Stack Developer | Team Lead' 'Vue Developer'
 'React Native Developer' 'Senior API Developer'
 'Senior Unity Developer, gt.school (Remote) - $100,000/year USD'
 'Senior React js Developer'
 'Senior Mobile Developer, gt.school (Remote) - $100,000/year USD'
 'Senior Dotnet Developer'
 'Mobile Application Developer (iOS, Swift), gt.school (Remote) - $100,000/year USD'
 'iOS Developer, gt.school (Remote) - $100,000/year USD'
 'Wordpress/PHP Developer With React.js' 'Senior MEAN/MERN Developer'
 'Senior Java Developer' 'Senior Software Developer'
 'Azure Full Stack Developer'
 'Full-Stack Web Developer (Django Developer)' 'Mean Stack Developer'
 'MEAN Stack Developer' 'Senior Backend Developer (Python)'
 'Full Stack Developer (Laravel, My SQL, React JS)' 'Blockchain Developer'
 'Senior Shopify Developer' 'Lead Dotnet Developer'
 'Trainee Unreal engine developer' 'Bubble.io Developer' 'React Developer'
 'Vue.Js Developer'
 '🚀 Seeking a Talented Angular Software Developer to Join Our Startup Team!'
 'Enterprise Resources Planning Developer'
 'Webflow Developer and Graphic Designer' 'Junior PHP Laravel Developer'
 'Laravel PHP Developer' 'Senior React Js Developer'
 'WordPress Plugin Developer JD' 'Senior Core PHP Developer'
 'PHP/ Wordpress Developer' 'ODOO Software Developer'
 'Mid/Senior Vue and Nuxt.js Developer' 'Full-Stack Developer'
 'Junior Database developers with Azure Data Lake - Full Remote - Contractor in USD'
 'Django Developer' 'Web Developer - WordPress' 'Apex Developer'
 'Front End Shopify Developer' 'Senior Full stack Developer'
 'Senior Full-Stack Developer' 'Senior Blockchain Developer'
 'Senior Shopify developer' 'PHP Web Developer'
 'C++ Developer, Trilogy (Remote) - $200,000/year USD'
 'Unity Game Developer, gt.school (Remote) - $100,000/year USD'
 'Unity Developer, gt.school (Remote) - $100,000/year USD'
 'Full Stack Developer, Trilogy (Remote) - $100,000/year USD'
 'Senior Developer, Trilogy (Remote) - $100,000/year USD'
 'Experienced Full-Stack Developer with Web Development Experience (Remote Position)'
 'Java Developer' 'Unreal Developer'
 'Node.js Developer for Lahore and Faisalabad'
 'Senior .Net Developer (Integrations)' 'Senior Wordpress Developer'
 'Senior Salesforce Developer' 'Python Backend developer'
 'Angular & NodeJs Developer' 'Senior Developer (Web & SAP Business One)'
 'Backend Developer Node.js / Nest / Typescript (Karachi)'
 'Backend Developer' 'Senior Web Application Developer'
 'React-Native Developer' 'Wordpress Plugin Developers' 'Vue JS Developer'
 'Senior Full Stack Developer' 'POWER BI Developer'
 'Cross-Platform Mobile Developers M5164'
 'Cross-Platform Mobile Developer M5164'
 'Internship Program - Angular frontend developer'
 'Full-Stack Back-End-Heavy Developer' 'Senior Developer'
 'Power Platform Developer (Remote)' 'Business Developer'
 'Business developer' 'Python and PHP Developer'
 'Lead Site Speed Optimization Developer - Front End Engineer'
 'RPA Developer' 'WPF Developer' 'BLOCKCHAIN FULL STACK DEVELOPER'
 'Senior Deep Learning Developer (Text To Speech / TTS)'
 'PHP Developer (laravel and Core PHP)' 'Principal Dotnet Developer'
 'Senior Frontend Developer' 'Vuejs Developer'
 'Cross Platform Mobile Developer' 'SAP ABAP Developer'
 'Senior Backend Developer'
 'Backend Developer (Custom WordPress and Laravel)'
 'Senior Mobile and AI Application Developer' 'PHP And Laravel Developer'
 'Full-Stack Developer (Node/ Nest/ Typescript/ Rest-API)'
 'Senior Full-stack Java / Angular Developer - +10 years of IT experience - Full remote - Contractor in USD'
 'Senior .Net MAUI /Xamarin developer' 'GitHub Developer'
 'Swift Developer' 'Drupal Developer - Full remote - Contractor in USD'
 'Java/React Developer'
 'Java / Angular Software Developer - +3 years - Contractor in USD'
 'No Code Developer' 'Python Django developer' 'Trainee Laravel Developer'
 'Creative Unity Developer' 'swift developer' 'Full Stack web developer'
 'Associate Flutter Developer' 'Oracle Apex Developer' 'Node Js Developer'
 'Node Js. Developer' 'Mobile Application Developer(React Native)'
 'VUE JS Front End Developer' 'PHP Core Developer'
 'ASP.NET Senior Lead Developer' 'Front End Angular Developer'
 'Senior Salesforce Developer - Architecture'
 'Senior Javascript Developer' 'Senior MEAN Stack Developer'
 'Internship For PHP Laravel Developer' 'Fintech Developer'
 'Web Application Developer'
 'Senior IOS Developer, gt.school (Remote) - $100,000/year USD'
 'ServiceNow Developer' 'Senior Business Developer' 'MERN/MEAN Developer'
 'Sr. Python Developer' 'Jr. Instructional Designer and Developer'
 'PHP AND LARAVEL DEVELOPER' '.NET Developer with Xamarin Experience'
 'Unity Game Developer' 'WordPress Full Stack Developer'
 'Java Developer (Backend)' 'Back End Developer Node JS'
 'Drupal 9/10 Developer - Full remote - Contractor in USD'
 'ERP Developer (Python / JS / MySQL)' 'Word Press Developer'
 'Technical Support Engineer, Developer Support'
 'Flutter Developer (Contractual)' 'Wordpress Plugin Developer'
 'Senior .Net Core/Angular Developer' 'Senior Nodejs Developer'
 'Shopilify Cms developer' 'UNREAL DEVELOPER' 'SQL Developer'
 'MicroStrategy Developer' 'Senior Deep Learning Developer'
 'NetSuite Developer' 'Node JS Developer' 'Marketo Developer'
 'Associate Developer, Java' 'Oracle Developer'
 'Full-Stack Cloud Developer' 'Senior Front-End Developer'
 'Solana Developer' 'Senior Web Developer (PHP+WordPress)'
 'Web Application Developer (AR and XML)' 'Senior PHP/Wordpress Developer'
 'Cybersecurity Software Developer' 'Full Stack Developer (PHP)'
 'PHP/Laravel Developer'
 'Microsoft Dynamics 365 Commerce/Retail CRT Developer (Freelance)'
 'Back-End Developer' 'PHP Laravel Developer' 'Nodejs Developer'
 'SSRS Developer' 'Senior Mobile Application Developer'
 'Full Stack developer' 'Azure Backend Developer'
 'BI Engineer/Looker Dashboard Developer' 'Software Developer in Test'
 'Senior Integration Developer - Onsite in Dubai'
 'Full Stack Developer - Onsite in Dubai'
 'Django React Full Stack Developer' 'Jr Android Developer'
 'Lead Full Stack Web Developer' 'Golang Developer'
 'Oracle APEX Developer' 'MERN STACK Developer' 'Drupal Developer'
 'Senior Mobile App Developer' 'Mid - Senior Unity Developer'
 'Angular/Node Developer' 'Senior Dotnet + React Developer'
 'Senior Back End Developer' 'Senior .Net Full Stack Developer'
 'Power Platform Developer' 'Node js  developer'
 'Full Stack NextJS Developer' 'Senior Dot Net Developer'
 'Senior Python/Django Developer'
 'Senior Backend Developer - Onsite Job Role - Night Shift'
 'Web Developer / WordPress Developer Apprentice (Unpaid)'
 'PHP & JavaScript Developer (WordPress/WooCommerce Specialist)'
 'Senior BlockChain Developer' 'Senior WordPress Developer'
 'Javascript/Angular Developer'
 'Senior SharePoint Developer with strong Power Platform Integration'
 'Shopify Developer (Liquid)' 'Senior Azure Cloud Developer'
 'Mobile Apps (Xamarin) - Software Developer'
 'WordPress Backend Developer' 'iOS Developer (Jr Level)'
 'Senior IOS Developer']


Number of Unique values in filtered_df_title:304


count of_un_complete_desc in filtered_df_title:11
count of Null desc in filtered_df_title:7
count of abonormal desc in filtered_df_title:18


length of filtered_df_desc:507


Unique values in filtered_df_desc:
['SQL Database Developer' 'Business Intelligence Developer'
 'Web Developer - Internship' 'Dotnet+React Developer'
 'Artificial Intelligence Developer' 'Junior Business Developer'
 'Full Stack Developer' 'Python Developer with Data Science Focus'
 'Odoo Developer' 'Web Developer' 'SOFTWARE DEVELOPER'
 'Salesforce Developer' 'SEO Developer' 'Python/Django Developer'
 'Application Developer' 'Back End Developer' 'Shopify Developer'
 'Junior Dotnet Developer' 'Associate MERN Stack Developer'
 'TV App Developer' 'Wordpress Developer' 'Dotnet Developer'
 'PHP Developer Required'
 'AI-Augmented Software Developer, Trilogy (Remote) - $200,000/year USD'
 'Shopify App Developer' 'Full Stack Dotnet Developer'
 'Lead Web Developer' 'Senior Web Developer' 'Scala Developer'
 'Senior Python Developer' 'HubSpot Developer' 'MERN Stack Developer'
 'Node.JS Developer' 'Software Developer'
 'Full stack Developer (Mid-Level)' '.Net Developer - C# - MVC'
 'Microsoft Dynamics 365 CRM Developer' 'Trainee iOS Developer'
 'Mern Stack Developer'
 'MERN Stack Developer - ReactJS, NodeJS, Apollo, Graphql & MongoDB'
 'Full Stack Developer (.Net & Angular)' 'Game Developer'
 'full stack developer' 'Javascript Developer'
 'mid Lavel Laravel Developer' 'MERN and React Native Developer'
 'Software Architect Lead Developer' 'Node.Js Developer'
 'Senior .NET Developer/Lead' 'Full Stack PHP developer'
 'Senior Mern Stack Developer'
 'Senior Full Stack Web Developer (PHP Laravel, VueJS, NodeJS)'
 'Unity Developer' 'Mobile Application Developer' 'Laravel Developer'
 'iOS Developer' 'Senior MERN STACK Developer'
 'Frontend Vue j.s developer' 'Sr Flutter Developers'
 'Lead Java Developer' 'Angular developer' 'Senior Node JS Developer'
 'Lead ReactJS Developer - Web TV Application'
 'Senior MERN Stack Developer' 'Senior React Native Developer'
 'Senior PHP Developer' 'Senior Fullstack Elixir Developer'
 'Sr. React Native developer' 'Junior Backend Developer (Python)'
 'Frontend Developer' 'Python Developer'
 'AI-Augmented Software Developer, Skyvera (Remote) - $200,000/year USD'
 'User Interface Developer' 'Front-End Developer' 'flutter Developer'
 'Shopify Back End Developer' 'Full Stack Dotnet Developer with Angular'
 'International Business Trade Developer- Pakistan/Bangladesh'
 'ReactJS Developer' 'Full Stack Developer with 1.5 Years of Experience'
 'Software/Application Developer' 'Magento Developer'
 'Flutter Application Developer' 'PHP Developer' 'Dot Net Core Developer'
 'Flutter Developer' 'PHP Backend Developer'
 'Senior MERN Stack Developer | Team Lead' 'Vue Developer'
 'React Native Developer' 'Sr. Angular Developer' 'Senior API Developer'
 'Senior Unity Developer, gt.school (Remote) - $100,000/year USD'
 'Senior React js Developer'
 'Senior Mobile Developer, gt.school (Remote) - $100,000/year USD'
 'Senior Dotnet Developer'
 'Mobile Application Developer (iOS, Swift), gt.school (Remote) - $100,000/year USD'
 'iOS Developer, gt.school (Remote) - $100,000/year USD'
 'Wordpress/PHP Developer With React.js' 'Senior MEAN/MERN Developer'
 'Senior Java Developer' 'Senior Software Developer'
 'Azure Full Stack Developer'
 'Full-Stack Web Developer (Django Developer)' 'Mean Stack Developer'
 'MEAN Stack Developer' 'Senior Backend Developer (Python)'
 'Full Stack Developer (Laravel, My SQL, React JS)' 'Blockchain Developer'
 'Senior Shopify Developer' 'Angular Developer' 'Lead Dotnet Developer'
 'Trainee Unreal engine developer' 'Bubble.io Developer' 'React Developer'
 'Android Developer' 'Vue.Js Developer'
 '🚀 Seeking a Talented Angular Software Developer to Join Our Startup Team!'
 'Webflow Developer and Graphic Designer' 'Junior PHP Laravel Developer'
 'Laravel PHP Developer' 'Senior React Js Developer'
 'WordPress Plugin Developer JD' 'Senior Core PHP Developer'
 'PHP/ Wordpress Developer' 'ODOO Software Developer'
 'Mid/Senior Vue and Nuxt.js Developer' 'Full-Stack Developer'
 'Junior Database developers with Azure Data Lake - Full Remote - Contractor in USD'
 'Django Developer' 'Apex Developer' 'Front End Shopify Developer'
 'Senior Full stack Developer' 'Senior Full-Stack Developer'
 'Senior Blockchain Developer' 'Senior Shopify developer'
 'PHP Web Developer' 'C++ Developer, Trilogy (Remote) - $200,000/year USD'
 'Unity Game Developer, gt.school (Remote) - $100,000/year USD'
 'Unity Developer, gt.school (Remote) - $100,000/year USD'
 'Full Stack Developer, Trilogy (Remote) - $100,000/year USD'
 'Senior Developer, Trilogy (Remote) - $100,000/year USD'
 'Experienced Full-Stack Developer with Web Development Experience (Remote Position)'
 'Java Developer' 'Node.js Developer for Lahore and Faisalabad'
 'Senior .Net Developer (Integrations)' 'Senior Wordpress Developer'
 'Senior Salesforce Developer' 'Python Backend developer'
 'Angular & NodeJs Developer' 'Senior Developer (Web & SAP Business One)'
 'Backend Developer Node.js / Nest / Typescript (Karachi)'
 'Backend Developer' 'Senior Web Application Developer'
 'React-Native Developer' 'Wordpress Plugin Developers' 'Vue JS Developer'
 'Senior Full Stack Developer' 'POWER BI Developer'
 'Cross-Platform Mobile Developers M5164'
 'Cross-Platform Mobile Developer M5164'
 'Internship Program - Angular frontend developer'
 'Full-Stack Back-End-Heavy Developer' 'Senior Developer'
 'Power Platform Developer (Remote)' 'Business Developer'
 'Business developer' 'Python and PHP Developer'
 'Lead Site Speed Optimization Developer - Front End Engineer'
 'RPA Developer' 'WPF Developer' 'BLOCKCHAIN FULL STACK DEVELOPER'
 'Senior Deep Learning Developer (Text To Speech / TTS)'
 'PHP Developer (laravel and Core PHP)' 'Principal Dotnet Developer'
 'Senior Frontend Developer' 'Vuejs Developer'
 'Cross Platform Mobile Developer' 'SAP ABAP Developer'
 'Senior Backend Developer' 'Senior Mobile and AI Application Developer'
 'PHP And Laravel Developer'
 'Full-Stack Developer (Node/ Nest/ Typescript/ Rest-API)'
 'Senior .Net MAUI /Xamarin developer' 'GitHub Developer'
 'Swift Developer' 'Drupal Developer - Full remote - Contractor in USD'
 'Java/React Developer'
 'Java / Angular Software Developer - +3 years - Contractor in USD'
 'No Code Developer' 'Python Django developer' 'Trainee Laravel Developer'
 'swift developer' 'Full Stack web developer'
 'Associate Flutter Developer' 'Oracle Apex Developer' 'Node Js Developer'
 'Node Js. Developer' 'Mobile Application Developer(React Native)'
 'VUE JS Front End Developer' 'PHP Core Developer'
 'ASP.NET Senior Lead Developer' 'Front End Angular Developer'
 'Senior Salesforce Developer - Architecture'
 'Senior Javascript Developer' 'Senior MEAN Stack Developer'
 'Internship For PHP Laravel Developer' 'Fintech Developer'
 'Web Application Developer'
 'Senior IOS Developer, gt.school (Remote) - $100,000/year USD'
 'ServiceNow Developer' 'Senior Business Developer' 'MERN/MEAN Developer'
 'Sr. Python Developer' 'Jr. Instructional Designer and Developer'
 'PHP AND LARAVEL DEVELOPER' '.NET Developer with Xamarin Experience'
 'Unity Game Developer' 'WordPress Full Stack Developer'
 'Java Developer (Backend)' 'Back End Developer Node JS'
 'Drupal 9/10 Developer - Full remote - Contractor in USD'
 'ERP Developer (Python / JS / MySQL)' 'Word Press Developer'
 'Technical Support Engineer, Developer Support'
 'Wordpress Plugin Developer' 'Senior .Net Core/Angular Developer'
 'Senior Nodejs Developer' 'Shopilify Cms developer' 'UNREAL DEVELOPER'
 'SQL Developer' 'MicroStrategy Developer'
 'Senior Deep Learning Developer' 'NetSuite Developer' 'Node JS Developer'
 'Marketo Developer' 'Associate Developer, Java' 'Oracle Developer'
 'Full-Stack Cloud Developer'
 'Senior Full-stack Java / Angular Developer - +10 years of IT experience - Full remote - Contractor in USD'
 'Senior Front-End Developer' 'Solana Developer'
 'Senior Web Developer (PHP+WordPress)'
 'Web Application Developer (AR and XML)' 'Senior PHP/Wordpress Developer'
 'Cybersecurity Software Developer' 'Full Stack Developer (PHP)'
 'PHP/Laravel Developer'
 'Microsoft Dynamics 365 Commerce/Retail CRT Developer (Freelance)'
 'Back-End Developer' 'PHP Laravel Developer' 'Nodejs Developer'
 'SSRS Developer' 'Senior Mobile Application Developer'
 'Full Stack developer' 'Azure Backend Developer'
 'BI Engineer/Looker Dashboard Developer' 'Software Developer in Test'
 'Senior Integration Developer - Onsite in Dubai'
 'Full Stack Developer - Onsite in Dubai'
 'Django React Full Stack Developer' 'Jr Android Developer'
 'Lead Full Stack Web Developer' 'Golang Developer'
 'Oracle APEX Developer' 'MERN STACK Developer' 'Drupal Developer'
 'Senior Mobile App Developer' 'Mid - Senior Unity Developer'
 'Angular/Node Developer' 'Senior Dotnet + React Developer'
 'Senior Back End Developer' 'Senior .Net Full Stack Developer'
 'Power Platform Developer' 'Node js  developer'
 'Full Stack NextJS Developer' 'Senior Dot Net Developer'
 'Senior Python/Django Developer'
 'Senior Backend Developer - Onsite Job Role - Night Shift'
 'Web Developer / WordPress Developer Apprentice (Unpaid)'
 'PHP & JavaScript Developer (WordPress/WooCommerce Specialist)'
 'Senior BlockChain Developer' 'Senior WordPress Developer'
 'Javascript/Angular Developer'
 'Senior SharePoint Developer with strong Power Platform Integration'
 'Shopify Developer (Liquid)' 'Senior Azure Cloud Developer'
 'WordPress Backend Developer' 'iOS Developer (Jr Level)'
 'Senior IOS Developer']


Number of Unique values in filtered_df_desc:290


It is nearly 98.49906191369607 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 14 job titles which present in filtered_df_title but not present in filtered_df_desc:

In [ ]:
df_3[df_3['Job Title']=='WordPress backend developer']['Job Desception']

'Business developer'
'Senior .net core API developer'
['Jr Business Developer (Upwork)', 'WordPress backend developer', 'Unreal Developer', 'Flutter Developer (Contractual)', 'Mobile Apps (Xamarin) - Software Developer']

### Analyzing software keyword

In [ ]:
it_tech_pattern = 'Software'
case=False # 230 for True and 235 for Flase
filter_keyword(it_tech_pattern,df_3,case)

['PS Software Engineer', 'Mobile Apps (Xamarin) - Software Developer']

In [ ]:
### Analyzing Digital keyword

In [ ]:
it_tech_pattern = 'Digital'
case=True # 62 for True and 62 for Flase: 0 title for 'digital' 
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
### Analyzing virtual keyword

In [ ]:
it_tech_pattern = 'Virtual'
case=True # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

Number of Unique values in filtered_df_desc:3


It is nearly 21.052631578947366 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 10 job titles which present in filtered_df_title but not present in filtered_df_desc:
['Virtual Data Analytics Internship - Customer Insights', 'Virtual Data Engineering Internship - Performance Optimization', 'Virtual Data Analytics Internship - Customer Retention', 'Virtual Project Management Internship', 'Virtual Data Engineering Internship - Cloud Based Storage System', 'Virtual Data Engineering Internship - Payment Capabilities', 'Virtual B2B Sales Internship', 'Virtual Customer Experience Internship', 'Virtual Operations Management Internship', 'Virtual Product Management Internship']

In [ ]:
it_tech_pattern = 'Data'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [259]:
it_tech_pattern = 'app'
case=False # 21 for True and 533 for Flase
filter_keyword(it_tech_pattern,df_3,case)

length of filtered_df_title:51


Unique values in filtered_df_title:
['junior application support engineer' 'Application Developer'
 'TV App Developer' 'Application Support Analyst'
 'Application/Support Engineer'
 'Applications Operations and Management Consultant, Managed Services'
 'Shopify App Developer'
 'Microsoft Dynamics CRM and Power Apps Consultant'
 'Telesales Representative - Appointment Setter'
 'Mobile Application Developer'
 'Lead ReactJS Developer - Web TV Application'
 'Application Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'App Store Optimization (ASO) Manager' 'Software/Application Developer'
 'Web Administrator - Middleware Applications (WAS)'
 'Flutter Application Developer'
 'Mobile Application Developer (iOS, Swift), gt.school (Remote) - $100,000/year USD'
 'Application Associate, SNL Feeds' 'Manager Frontend App Development'
 'Business Application Manager' 'Appointment Setter'
 'Administrative Assistant (Temporary Appointment), GS-5, Islamabad, Pakistan, # 26003'
 'Senior Web Application Developer'
 'Senior Mobile and AI Application Developer'
 'Windows Application Architect'
 'Mobile Application Developer(React Native)'
 'Cloud Automation & Application Engineer(Team Lead)'
 'Practice Manager - Microsoft Cloud Apps & Integration - based in Perth, Australia'
 'Application Support Engineer' 'Web Application Developer'
 'Technical Application Specialist - Molecular Diagnosis'
 'Creative Video Editor for Apps Promotions & Ad Campaigns.'
 'Mobile Games Acquisition Manager (App Store Optimization)'
 'Web Application Developer (AR and XML)'
 'Senior Mobile Application Developer'
 'Sap Advanced Business Application Programming Consultant'
 'Senior Mobile App Developer'
 'Web Developer / WordPress Developer Apprentice (Unpaid)'
 'Mobile Apps (Xamarin) - Software Developer'
 'Oracle Apps DBA - R12 (Full Customization)']


Number of Unique values in filtered_df_title:40


count of_un_complete_desc in filtered_df_title:1
count of Null desc in filtered_df_title:0
count of abonormal desc in filtered_df_title:1


length of filtered_df_desc:43


Unique values in filtered_df_desc:
['junior application support engineer' 'Application Developer'
 'TV App Developer' 'Application Support Analyst'
 'Application/Support Engineer'
 'Applications Operations and Management Consultant, Managed Services'
 'Shopify App Developer'
 'Microsoft Dynamics CRM and Power Apps Consultant'
 'Mobile Application Developer'
 'Lead ReactJS Developer - Web TV Application'
 'Application Support Engineer, Skyvera (Remote) - $30,000/year USD'
 'App Store Optimization (ASO) Manager' 'Software/Application Developer'
 'Web Administrator - Middleware Applications (WAS)'
 'Flutter Application Developer'
 'Mobile Application Developer (iOS, Swift), gt.school (Remote) - $100,000/year USD'
 'Application Associate, SNL Feeds' 'Manager Frontend App Development'
 'Business Application Manager' 'Appointment Setter'
 'Administrative Assistant (Temporary Appointment), GS-5, Islamabad, Pakistan, # 26003'
 'Senior Web Application Developer'
 'Senior Mobile and AI Application Developer'
 'Windows Application Architect'
 'Mobile Application Developer(React Native)'
 'Practice Manager - Microsoft Cloud Apps & Integration - based in Perth, Australia'
 'Web Application Developer'
 'Technical Application Specialist - Molecular Diagnosis'
 'Mobile Games Acquisition Manager (App Store Optimization)'
 'Web Application Developer (AR and XML)'
 'Senior Mobile Application Developer' 'Application Support Engineer'
 'Sap Advanced Business Application Programming Consultant'
 'Senior Mobile App Developer'
 'Web Developer / WordPress Developer Apprentice (Unpaid)'
 'Oracle Apps DBA - R12 (Full Customization)']


Number of Unique values in filtered_df_desc:36


It is nearly 86.27450980392157 % varified by Jobs desc that It belongs to IT and Tech Jobs


list of 4 job titles which present in filtered_df_title but not present in filtered_df_desc:
['Telesales Representative - Appointment Setter', 'Cloud Automation & Application Engineer(Team Lead)', 'Creative Video Editor for Apps Promotions & Ad Campaigns.', 'Mobile Apps (Xamarin) - Software Developer']


List of 0 titles that are not cleared as IT and Tech Job due to abnoramal desc:
[]


List of  4 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['Telesales Representative - Appointment Setter', 'Cloud Automation & Application Engineer(Team Lead)', 'Creative Video Editor for Apps Promotions & Ad Campaigns.', 'Mobile Apps (Xamarin) - Software Developer']

List of  6 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['PowerBi Data Analyst', 'Virtual Data Analytics Internship - Customer Insights', 'Virtual Data Engineering Internship - Performance Optimization', 'Virtual Data Analytics Internship - Customer Retention', 'Virtual Data Engineering Internship - Cloud Based Storage System', 'Virtual Data Engineering Internship - Payment Capabilities']

In [ ]:
it_tech_pattern = 'AI'
case=True # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

Good

In [ ]:
it_tech_pattern = 'Computer'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

List of  1 titles that are not cleared as IT and Tech Job due to not matching of II_keywords in desc:
['Professor of Mechanical Engineering / Professor of Pharmacy/ PHD Computer Science']

In [ ]:
it_tech_pattern = 'Quality'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

['Software Quality Assurance Analyst', 'Product Quality Associate - MEA', 'Senior Care Quality Assurance Associate', 'Quality Operations Manager', 'Quality System Lead (Jamshoro)', 'Business Development Executive (Quality Assurance)', 'Assistant Manager - Quality']

In [ ]:
it_tech_pattern = 'Engineer'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)
# check all engineer titles in filtered_df_desc

['Trainee R&D Engineer', 'Software Engineer-Integration', 'Principal Software Engineer (khi/lhr/Isl)', '5-10 yr Experienced professionals: biofuels engineer + Experienced SME supply chain manager + Sectoral researcher', 'Civil Engineers (Roads, QA/QC) QS', 'Embedded System Engineer', 'One Identity Resident Engineer', 'Senior Process Design Engineer', 'Virtual Data Engineering Internship - Performance Optimization', 'Virtual Data Engineering Internship - Cloud Based Storage System', 'Virtual Data Engineering Internship - Payment Capabilities', 'Principal Software Engineer, GFI Software (Remote) - $100,000/year USD', 'Civil Engineer', 'Associate Professor - Avionics Engineering', 'Process Design Engineer', 'Cloud Automation & Application Engineer(Team Lead)', 'Project Engineer', 'Sales Engineer', 'Sub Engineer', 'Engineer', 'Proposal Engineer', 'Electrical Electronic Engineer', 'Professor of Mechanical Engineering / Professor of Pharmacy/ PHD Computer Science', 'Mechanical Maintenance Engineer', 'PS Software Engineer', 'Assistant Engineer – Operations', 'Chief Engineer (Power Utility)', 'Pipeline Maintenance Engineer', 'Inspection Engineer', 'Deputy Chief Engineer (Mechanical - Gas Engine)']

In [ ]:
it_tech_pattern = 'Architect'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'writ'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'analyst'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

'Senior Financial Analyst'
'Analyst Client Care - Contract', 'Research Analyst/ Academic Writer', 'Senior Actuarial Analyst', 'Benefit Configuration Analyst'

In [ ]:
it_tech_pattern = 'market'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Research'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'designer'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Freelance'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Editor'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Creat'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Product'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Teacher'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'HR'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Finance'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Education'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Business'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'agricalture'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Anchor'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Sports'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'school'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'College'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'University'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'PHD'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'worker'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'tax'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'ML'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'sell'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Executive'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'data entry'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'admin'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'book'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Finance'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Finance'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

In [ ]:
it_tech_pattern = 'Finance'
case=False # 19 for True and 19 for Flase: 0 for virtual (small)
filter_keyword(it_tech_pattern,df_3,case)

import pandas as pd

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
it_tech_pattern = 'IT|Tech'
filtered_df = df[df['job_title'].str.contains(it_tech_pattern, case=False)]

import pandas as pd

it_tech_keywords = ['IT', 'Tech', 'Information Technology', 'Developer', 'Software Engineer', 'Data Scientist', ...]

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
filtered_df = df[df['job_title'].apply(lambda title: any(keyword in title for keyword in it_tech_keywords))]