In [1]:
import pandas as pd
import numpy as np

### reading Feature Eng processed csv file

In [2]:
df=pd.read_csv('Feature Eng processed Files/Linkedin_Job_Details_and_Descriptions_26-Sep-2023-to-26-Nov-202311737-jobs_20-features_685-pages_Feature-Eng-processed_v5.csv')

***This file have no duplicates and no missing values in Job details featues***

In [3]:
df

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info,company,location_1,location_2,Remote/Onsite,n_applicant,job posting time,Job Type nElements,Job-Type,Experience Level,Comp_N_Employees,Comp_Industry
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...,EcomFleet,Pakistan,Pakistan,Remote,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...,Digicon Valley,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...,Murkez Technologies,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,51-200 employees,Not specified
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...,DevNatives,Islamabad,"Islamabad, Islāmābād, Pakistan",Hybrid,51,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN,ItCreaters,Lahore,"Lahore, Punjab, Pakistan",On-site,51,1 week ago,1,Full-time,Not specified,Not specified,Not specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11732,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN,Codiea.io,Bahawalpur,"Bahawalpur, Punjab, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,1-10 employees,Not specified
11733,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN,Bank Alfalah Limited,Karāchi,"Karāchi, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,3,Full-time,Mid-Senior level,"5,001-10,000 employees",Banking
11734,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN,DPL,Islamabad,"Islamabad, Islāmābād, Pakistan \n1 week ago\...",On-site,83,1 week ago,3,Full-time,Entry level,51-200 employees,IT Services and IT Consulting
11735,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN,Level 3 BOS,Karachi,"Karachi Division, Sindh, Pakistan \n1 week a...",On-site,19,1 week ago,3,Full-time,Mid-Senior level,201-500 employees,Outsourcing and Offshoring Consulting
11736,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN,The Hive,Karachi,"Karachi Division, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,11-50 employees,Not specified

In [4]:
df.shape

(11737, 20)

In [5]:
df.isnull().sum()

Job Title                0
Job Info                 0
Job Type                 0
Job Link_x               0
employees                0
Job ID                   0
Job Link_y               0
Job Desception          31
Company Info          2916
company                  0
location_1               0
location_2               0
Remote/Onsite            0
n_applicant           4686
job posting time         0
Job Type nElements       0
Job-Type                 0
Experience Level         0
Comp_N_Employees         0
Comp_Industry            0
dtype: int64

In [6]:
df_3=df.copy()

In [7]:
df_4=df_3.dropna(subset=['Job Desception'])
df_4

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info,company,location_1,location_2,Remote/Onsite,n_applicant,job posting time,Job Type nElements,Job-Type,Experience Level,Comp_N_Employees,Comp_Industry
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...,EcomFleet,Pakistan,Pakistan,Remote,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...,Digicon Valley,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...,Murkez Technologies,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,51-200 employees,Not specified
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...,DevNatives,Islamabad,"Islamabad, Islāmābād, Pakistan",Hybrid,51,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN,ItCreaters,Lahore,"Lahore, Punjab, Pakistan",On-site,51,1 week ago,1,Full-time,Not specified,Not specified,Not specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11732,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN,Codiea.io,Bahawalpur,"Bahawalpur, Punjab, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,1-10 employees,Not specified
11733,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN,Bank Alfalah Limited,Karāchi,"Karāchi, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,3,Full-time,Mid-Senior level,"5,001-10,000 employees",Banking
11734,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN,DPL,Islamabad,"Islamabad, Islāmābād, Pakistan \n1 week ago\...",On-site,83,1 week ago,3,Full-time,Entry level,51-200 employees,IT Services and IT Consulting
11735,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN,Level 3 BOS,Karachi,"Karachi Division, Sindh, Pakistan \n1 week a...",On-site,19,1 week ago,3,Full-time,Mid-Senior level,201-500 employees,Outsourcing and Offshoring Consulting
11736,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN,The Hive,Karachi,"Karachi Division, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,11-50 employees,Not specified

In [8]:
df_4.shape

(11706, 20)

In [9]:
df_4_uncomplete_desc_IDs=[]
for i in range(0,len(df_4.iloc[:])):
    if len(df_4.iloc[i]['Job Desception'])<20:
        df_4_uncomplete_desc_IDs.append(df_4.iloc[i]['Job ID'])

In [10]:
df_4_uncomplete_desc_IDs
len(df_4_uncomplete_desc_IDs)

1125

In [11]:
df_4_uncomp_desc=df_4[df_4['Job ID'].isin(df_4_uncomplete_desc_IDs)]
df_4_uncomp_desc

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info,company,location_1,location_2,Remote/Onsite,n_applicant,job posting time,Job Type nElements,Job-Type,Experience Level,Comp_N_Employees,Comp_Industry
23,Digital Marketing Strategist and Planner,Prime Human Resource Services (Pvt) Ltd · Karā...,Full-time,https://www.linkedin.com/jobs/view/3727011545,"10,001+ employees",3727011545,https://www.linkedin.com/jobs/view/3727011545,About the job,NaN,Prime Human Resource Services (Pvt) Ltd,Karāchi,"Karāchi, Sindh, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,"10,001+ employees",Not specified
136,Software Engineer-Integration,People (Professional Employers Pvt Ltd) · Isla...,Full-time,https://www.linkedin.com/jobs/view/3727002795,"5,001-10,000 employees",3727002795,https://www.linkedin.com/jobs/view/3727002795,About the job,NaN,People (Professional Employers Pvt Ltd),Islamabad,"Islamabad, Islāmābād, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,"5,001-10,000 employees",Not specified
400,DevOps Engineer,"TecBrix · Lahore, Punjab, Pakistan (Remote) \...",Full-time,https://www.linkedin.com/jobs/view/3727012776/...,11-50 employees,3727012776,https://www.linkedin.com/jobs/view/3727012776,About the job,NaN,TecBrix,Lahore,"Lahore, Punjab, Pakistan",Remote,NaN,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
433,Real Estate Sales Agent,"Fajar Real Estate · Lahore, Punjab, Pakistan (...",Full-time,https://www.linkedin.com/jobs/view/3727005694/...,11-50 employees,3727005694,https://www.linkedin.com/jobs/view/3727005694,About the job,NaN,Fajar Real Estate,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
440,Google Ads Specialist,"RT WEB Solutions · Lahore District, Punjab, Pa...",Full-time,https://www.linkedin.com/jobs/view/3727058923/...,11-50 employees,3727058923,https://www.linkedin.com/jobs/view/3727058923,About the job,NaN,RT WEB Solutions,Lahore,"Lahore District, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11731,Senior Consultant- Business Consulting- Intern...,"EY in Pakistan · Karachi Division, Sindh, Pak...",Hybrid\n\n \nInternship\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767944882,"1,001-5,000 employees · Accounting",3767944882,https://www.linkedin.com/jobs/view/3767944882,About the job,NaN,EY in Pakistan,Karachi,"Karachi Division, Sindh, Pakistan \n1 week a...",Hybrid,6,1 week ago,3,Internship,Mid-Senior level,"1,001-5,000 employees",Accounting
11732,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN,Codiea.io,Bahawalpur,"Bahawalpur, Punjab, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,1-10 employees,Not specified
11734,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN,DPL,Islamabad,"Islamabad, Islāmābād, Pakistan \n1 week ago\...",On-site,83,1 week ago,3,Full-time,Entry level,51-200 employees,IT Services and IT Consulting
11735,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN,Level 3 BOS,Karachi,"Karachi Division, Sindh, Pakistan \n1 week a...",On-site,19,1 week ago,3,Full-time,Mid-Senior level,201-500 employees,Outsourcing and Offshoring Consulting
11736,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN,The Hive,Karachi,"Karachi Division, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,11-50 employees,Not specified

In [12]:
df_5=df_4.drop(df_4_uncomp_desc.index)
df_5

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info,company,location_1,location_2,Remote/Onsite,n_applicant,job posting time,Job Type nElements,Job-Type,Experience Level,Comp_N_Employees,Comp_Industry
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...,EcomFleet,Pakistan,Pakistan,Remote,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...,Digicon Valley,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...,Murkez Technologies,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,51-200 employees,Not specified
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...,DevNatives,Islamabad,"Islamabad, Islāmābād, Pakistan",Hybrid,51,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN,ItCreaters,Lahore,"Lahore, Punjab, Pakistan",On-site,51,1 week ago,1,Full-time,Not specified,Not specified,Not specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11727,Technical Sales Support Specialist,"BUZZMAX.CA · Karāchi, Sindh, Pakistan \n1 wee...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3765162094,11-50 employees,3765162094,https://www.linkedin.com/jobs/view/3765162094,About the job\n \n \nABOUT US BUZZM...,Telecommunications\n \n ...,BUZZMAX.CA,Karāchi,"Karāchi, Sindh, Pakistan \n1 week ago\n\n",On-site,57,1 week ago,2,Full-time,Not specified,11-50 employees,Not specified
11728,YouTube Channel Producer,"Senew Tech · Lahore District, Punjab, Pakistan...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767643794,"501-1,000 employees",3767643794,https://www.linkedin.com/jobs/view/3767643794,About the job\n \n \nWe are seeking...,Information Technology & Services\n ...,Senew Tech,Lahore,"Lahore District, Punjab, Pakistan \n1 week ago",On-site,NaN,1 week ago,2,Full-time,Not specified,"501-1,000 employees",Not specified
11729,Social Media Content Creator - Night Shift wit...,"Dymentions Pakistan · Karāchi, Sindh, Pakistan...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3769970428,11-50 employees · Marketing Services,3769970428,https://www.linkedin.com/jobs/view/3769970428,About the job\n \n \nJoin the Socia...,Marketing Services\n \n ...,Dymentions Pakistan,Karāchi,"Karāchi, Sindh, Pakistan \n2 weeks ago\n\n",On-site,64,2 weeks ago,3,Full-time,Entry level,11-50 employees,Marketing Services
11730,Design Sales agents,Self-employed · Pakistan \n1 week ago\n\n · 1...,Remote\n\n \nPart-time,https://www.linkedin.com/jobs/view/3766852400,Shayan Tauqeer is hiring for this job,3766852400,https://www.linkedin.com/jobs/view/3766852400,About the job\n \n \nCompany Descri...,NaN,Self-employed,Pakistan,Pakistan \n1 week ago\n\n,Remote,10,1 week ago,2,Part-time,Not specified,Not specified,Not specified
11733,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN,Bank Alfalah Limited,Karāchi,"Karāchi, Sindh, Pakistan \n1 week ago",On-site,NaN,1 week ago,3,Full-time,Mid-Senior level,"5,001-10,000 employees",Banking

#### using commen keywords used in IT and Tech

In [13]:
it_tech_keywords=['Python','Django']
it_tech_keywords
len(it_tech_keywords)

filtered_df_3_title = df_3[df_3['Job Title'].apply(lambda title: any(keyword.lower() in title.lower() for keyword in it_tech_keywords))]
filtered_df_3_title

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info,company,location_1,location_2,Remote/Onsite,n_applicant,job posting time,Job Type nElements,Job-Type,Experience Level,Comp_N_Employees,Comp_Industry
54,Python Developer with Data Science Focus,"Noveltysoft · Lahore, Punjab, Pakistan (On-sit...",Full-time,https://www.linkedin.com/jobs/view/3723360552,1-10 employees,3723360552,https://www.linkedin.com/jobs/view/3723360552,About the job\n \n\n \nObjective:Se...,Software Development\n \n ...,Noveltysoft,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,2 weeks ago,1,Full-time,Not specified,1-10 employees,Not specified
142,Python/Django Developer,"Crymzee Networks (Pvt.) Ltd. · Lahore, Punjab,...",Full-time,https://www.linkedin.com/jobs/view/3727025255,11-50 employees,3727025255,https://www.linkedin.com/jobs/view/3727025255,About the job\n \n\n \nPosition: Fu...,IT Services and IT Consulting\n \n ...,Crymzee Networks (Pvt.) Ltd.,Lahore,"Lahore, Punjab, Pakistan",On-site,51,2 weeks ago,1,Full-time,Not specified,11-50 employees,Not specified
315,Senior Python Developer,"TatbeeqSoft · Lahore, Punjab, Pakistan (On-sit...",Full-time,https://www.linkedin.com/jobs/view/3727050780/...,11-50 employees,3727050780,https://www.linkedin.com/jobs/view/3727050780,About the job\n \n\n \nRole Descrip...,Software Development\n \n ...,TatbeeqSoft,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
567,Junior Backend Developer (Python),"Kamayi · Lahore, Punjab, Pakistan (On-site) \...",Full-time,https://www.linkedin.com/jobs/view/3727532698,11-50 employees,3727532698,https://www.linkedin.com/jobs/view/3727532698,About the job\n \n\n \nJunior Pytho...,Human Resources Services\n \n ...,Kamayi,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,11-50 employees,Not specified
615,Python Developer,"Pursue Today · Lahore, Punjab, Pakistan (On-si...",Full-time,https://www.linkedin.com/jobs/view/3725533689,1-10 employees,3725533689,https://www.linkedin.com/jobs/view/3725533689,About the job\n \n\n \nRequirements...,Software Development\n \n ...,Pursue Today,Lahore,"Lahore, Punjab, Pakistan",On-site,NaN,1 week ago,1,Full-time,Not specified,1-10 employees,Not specified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11067,Trainee Python Developer,"MAAQ Services · Lahore, Punjab, Pakistan \n5 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767396223,11-50 employees,3767396223,https://www.linkedin.com/jobs/view/3767396223,About the job\n \n \nAs a Trainee P...,IT Services and IT Consulting\n \n ...,MAAQ Services,Lahore,"Lahore, Punjab, Pakistan \n5 days ago",On-site,NaN,5 days ago,2,Full-time,Not specified,11-50 employees,Not specified
11357,Principal/Staff Data Engineer - ETL/AWS/Python...,"10Pearls · Islamabad, Islāmābād, Pakistan \n2...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767003267,"1,001-5,000 employees · IT Services and IT Con...",3767003267,https://www.linkedin.com/jobs/view/3767003267,About the job\n \n \nCompany Overvi...,IT Services and IT Consulting\n \n ...,10Pearls,Islamabad,"Islamabad, Islāmābād, Pakistan \n2 weeks ago...",On-site,42,2 weeks ago,3,Full-time,Mid-Senior level,"1,001-5,000 employees",IT Services and IT Consulting
11401,"Senior Fullstack Engineer (React, Django) - Re...",DropYacht · Pakistan \n2 weeks ago\n\n · 154 ...,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3769164219,11-50 employees · Marketing Services,3769164219,https://www.linkedin.com/jobs/view/3769164219,About the job\n \n \nJoin us as a l...,Marketing Services\n \n ...,DropYacht,Pakistan,Pakistan \n2 weeks ago\n\n,Remote,154,2 weeks ago,3,Full-time,Mid-Senior level,11-50 employees,Marketing Services
11473,Python Data Scientist,Turing · Pakistan \n1 week ago,Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771887505,"1,001-5,000 employees · IT Services and IT Con...",3771887505,https://www.linkedin.com/jobs/view/3771887505,About the job\n \n \nA U.S.-based c...,IT Services and IT Consulting\n \n ...,Turing,Pakistan,Pakistan \n1 week ago,Remote,NaN,1 week ago,3,Full-time,Mid-Senior level,"1,001-5,000 employees",IT Services and IT Consulting
11554,Python Django Developer,"Eurus Technologies · Islamabad, Islāmābād, Pa...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3766002060,51-200 employees,3766002060,https://www.linkedin.com/jobs/view/3766002060,About the job\n \n \nPositions: 2Lo...,Software Development\n \n ...,Eurus Technologies,Islamabad,"Islamabad, Islāmābād, Pakistan Reposted \n1 ...",On-site,NaN,1 week ago,2,Full-time,Not specified,51-200 employees,Not specified

In [14]:
filtered_df_3_title['Job Title'].unique()

array(['Python Developer with Data Science Focus',
       'Python/Django Developer', 'Senior Python Developer',
       'Junior Backend Developer (Python)', 'Python Developer',
       'Full-Stack Web Developer (Django Developer)',
       'Senior Backend Developer (Python)', 'Django Developer',
       'Senior Python Engineer for UK Consultant',
       'Data Lake Migration Expert to AWS & Python Expert',
       'Python Backend developer', 'Python and PHP Developer',
       'Head of Software Engineering (Python)', 'Python Django developer',
       'Python Team Lead', 'Software Engineer III-Django',
       'Software Architect - Python', 'Sr. Python Developer',
       'ERP Developer (Python / JS / MySQL)', 'Python Data Scientist',
       'Django React Full Stack Developer',
       'Senior Python/Django Developer', 'Python Backend Engineer',
       'Unreal Engine + Python AI developer', 'Technical Lead - Python',
       'Senior Backend Engineer - Python',
       'Web Scraper / Python Developer',
       'Chrome Extension & Python Developer',
       'Lead Python (Django) Engineer',
       'Full Stack Python (Django + React) Developer',
       'Python/Azure Data Engineer',
       'Python Developer - Deep Learning and Trading Backtesting',
       'Job Opportunity: Hiring Senior Python Backend Developer',
       'Seeking Full Stack Developer - Python, React, AWS, DevOps',
       'Data Science & Web Scraping for AI (Python, LangChain, SQL, Automation)',
       'Python - Data Ingestion',
       '(Remote) Data Engineer, Python, AWS Redshift',
       'Trainee Python Developer',
       'Principal/Staff Data Engineer - ETL/AWS/Python/Apache',
       'Senior Fullstack Engineer (React, Django) - Remote',
       'Python Django Developer'], dtype=object)

In [15]:
len(filtered_df_3_title['Job Title'].unique())

41

In [16]:
titles_to_drop=[]
titles_to_drop
len(titles_to_drop)

0

In [17]:
df_3_filtered=filtered_df_3_title[~filtered_df_3_title['Job Title'].isin(titles_to_drop)]
df_3_filtered
len(df_3_filtered)

77

In [18]:
len(df_3_filtered['Job Title'].unique())

41

In [19]:
path=f"Filltered_Files/k-{it_tech_keywords[0]}_26_sep_to_26_nov_{len(df_3_filtered)}_jobs_{len(df_3_filtered['Job Title'].unique())}_titles_v5_Feature_Eng_Processed.csv"
path

'Filltered_Files/k-Python_26_sep_to_26_nov_77_jobs_41_titles_v5_Feature_Eng_Processed.csv'

In [22]:
# df_3_filtered.to_csv(path,index=False)

import pandas as pd

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
it_tech_pattern = 'IT|Tech'
filtered_df = df[df['job_title'].str.contains(it_tech_pattern, case=False)]

import pandas as pd

it_tech_keywords = ['IT', 'Tech', 'Information Technology', 'Developer', 'Software Engineer', 'Data Scientist', ...]

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
filtered_df = df[df['job_title'].apply(lambda title: any(keyword in title for keyword in it_tech_keywords))]