In [1]:
import pandas as pd
import numpy as np

In [2]:
df_1=pd.read_csv('Files used in current analysis/Linkedin_Job_Details_26-Sep-2023-to-26-Nov-2023_15875-jobs_685-pages.csv')
df_1

,Job Title,Job Info,Job Type,Job Link,employees
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job
...,...,...,...,...,...
15870,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking"
15871,Release Support Engineer,Turing · Pakistan Reposted \n1 week ago,Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3766809535,"1,001-5,000 employees · IT Services and IT Con..."
15872,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting
15873,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...
15874,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees

In [3]:
df_2=pd.read_csv('Files used in current analysis/Linkedin_Job-Descriptions-company_details_26-Sep-2023-to-26-Nov-2023_15947-jobs_685-pages.csv')
df_2

,Job Link,Job Desception,Company Info
0,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...
15942,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN
15943,https://www.linkedin.com/jobs/view/3766809535,About the job\n \n \nA U.S.-based c...,IT Services and IT Consulting\n \n ...
15944,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
15945,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
15946,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [4]:
df_1['Job ID']=df_1['Job Link'].apply(lambda x:int(x.split('/')[5]))
df_2['Job ID']=df_2['Job Link'].apply(lambda x:int(x.split('/')[5]))

In [5]:
# df_1[df_1['Job ID'].isin(df_2['Job ID'])]
# df_2[df_2['Job ID'].isin(df_1['Job ID'])]
# pd.merge(df_1[df_1['Job ID'].isin(df_2['Job ID'])],df_2[df_2['Job ID'].isin(df_1['Job ID'])])
# pd.merge(df_1[df_1['Job ID'].isin(df_2['Job ID'])],df_2[df_2['Job ID'].isin(df_1['Job ID'])]).drop_duplicates(subset=['Job ID']).shape

In [5]:
df_3=pd.merge(df_1,df_2,on='Job ID',how='inner')
df_3

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
27639,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN
27640,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN
27641,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
27642,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
27643,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [7]:
# why df_3 have 27644 rows

In [8]:
df_1.drop_duplicates(subset=['Job ID']).shape

(12010, 6)

In [9]:
df_2.drop_duplicates(subset=['Job ID']).shape

(12321, 4)

In [10]:
df_3.drop_duplicates(subset=['Job ID']).shape

(12010, 9)

In [6]:
df_1.isnull().sum()

Job Title    288
Job Info     288
Job Type     302
Job Link       0
employees    303
Job ID         0
dtype: int64

In [12]:
df_2.isnull().sum()

Job Link             0
Job Desception     315
Company Info      4084
Job ID               0
dtype: int64

In [7]:
df_3.isnull().sum()

Job Title          348
Job Info           348
Job Type           362
Job Link_x           0
employees          363
Job ID               0
Job Link_y           0
Job Desception     385
Company Info      6478
dtype: int64

***why there are 348 Null values in Job Title instead of 288***

In [14]:
df_3.columns

Index(['Job Title', 'Job Info', 'Job Type', 'Job Link_x', 'employees',
       'Job ID', 'Job Link_y', 'Job Desception', 'Company Info'],
      dtype='object')

In [15]:
df_1.dropna(inplace=True)
df_2.dropna(subset=['Job Desception'],inplace=True)
df_3.dropna(subset=['Job Title','Job Info','Job Type','employees'],inplace=True) # i want to delete specific columns

In [16]:
df_1.shape,df_2.shape,df_3.shape

((15572, 6), (15632, 4), (27281, 9))

In [17]:
df_1=df_1.drop_duplicates(subset=['Job ID'])
df_2=df_2.drop_duplicates(subset=['Job ID'])
df_3=df_3.drop_duplicates(subset=['Job ID'])

In [18]:
df_1.shape,df_2.shape,df_3.shape

((11744, 6), (12037, 4), (11744, 9))

In [19]:
12010-363

11647

In [20]:
df_3

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
27639,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN
27640,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN
27641,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
27642,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
27643,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [21]:
df_4=df_3.dropna(subset=['Job Desception'])
df_4

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
27639,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN
27640,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN
27641,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
27642,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
27643,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [22]:
df_4.shape

(11708, 9)

In [23]:
df_4_uncomplete_desc_IDs=[]
for i in range(0,len(df_4.iloc[:])):
    if len(df_4.iloc[i]['Job Desception'])<20:
        df_4_uncomplete_desc_IDs.append(df_4.iloc[i]['Job ID'])

In [24]:
df_4_uncomplete_desc_IDs
len(df_4_uncomplete_desc_IDs)

1125

In [25]:
df_4_uncomp_desc=df_4[df_4['Job ID'].isin(df_4_uncomplete_desc_IDs)]
df_4_uncomp_desc

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
120,Digital Marketing Strategist and Planner,Prime Human Resource Services (Pvt) Ltd · Karā...,Full-time,https://www.linkedin.com/jobs/view/3727011545,"10,001+ employees",3727011545,https://www.linkedin.com/jobs/view/3727011545,About the job,NaN
328,Software Engineer-Integration,People (Professional Employers Pvt Ltd) · Isla...,Full-time,https://www.linkedin.com/jobs/view/3727002795,"5,001-10,000 employees",3727002795,https://www.linkedin.com/jobs/view/3727002795,About the job,NaN
801,DevOps Engineer,"TecBrix · Lahore, Punjab, Pakistan (Remote) \...",Full-time,https://www.linkedin.com/jobs/view/3727012776/...,11-50 employees,3727012776,https://www.linkedin.com/jobs/view/3727012776,About the job,NaN
842,Real Estate Sales Agent,"Fajar Real Estate · Lahore, Punjab, Pakistan (...",Full-time,https://www.linkedin.com/jobs/view/3727005694/...,11-50 employees,3727005694,https://www.linkedin.com/jobs/view/3727005694,About the job,NaN
849,Google Ads Specialist,"RT WEB Solutions · Lahore District, Punjab, Pa...",Full-time,https://www.linkedin.com/jobs/view/3727058923/...,11-50 employees,3727058923,https://www.linkedin.com/jobs/view/3727058923,About the job,NaN
...,...,...,...,...,...,...,...,...,...
27638,Senior Consultant- Business Consulting- Intern...,"EY in Pakistan · Karachi Division, Sindh, Pak...",Hybrid\n\n \nInternship\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767944882,"1,001-5,000 employees · Accounting",3767944882,https://www.linkedin.com/jobs/view/3767944882,About the job,NaN
27639,Unity Developer,"Codiea.io · Bahawalpur, Punjab, Pakistan \n1 ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767951886,1-10 employees,3767951886,https://www.linkedin.com/jobs/view/3767951886,About the job,NaN
27641,Information Security Specialist,"DPL · Islamabad, Islāmābād, Pakistan \n1 week...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772530977,51-200 employees · IT Services and IT Consulting,3772530977,https://www.linkedin.com/jobs/view/3772530977,About the job,NaN
27642,FUNCTIONAL CONSULTANT ORACLE FUSION - HCM,"Level 3 BOS · Karachi Division, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3771943212,201-500 employees · Outsourcing and Offshoring...,3771943212,https://www.linkedin.com/jobs/view/3771943212,About the job,NaN
27643,Community Associate,"The Hive · Karachi Division, Sindh, Pakistan ...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767944844,11-50 employees,3767944844,https://www.linkedin.com/jobs/view/3767944844,About the job,NaN

In [26]:
df_5=df_4.drop(df_4_uncomp_desc.index)
df_5

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
0,LinkedIn Data Extractor,EcomFleet · Pakistan (Remote) \n1 week ago,Full-time,https://www.linkedin.com/jobs/view/3727054368,11-50 employees,3727054368,https://www.linkedin.com/jobs/view/3727054368,About the job\n \n\n \nAbout Us:We ...,Advertising Services\n \n ...
1,It Management Intern,"Digicon Valley · Lahore, Punjab, Pakistan (On-...",Full-time,https://www.linkedin.com/jobs/view/3723395858,11-50 employees,3723395858,https://www.linkedin.com/jobs/view/3723395858,About the job\n \n\n \nWe are looki...,IT Services and IT Consulting\n \n ...
2,SQL Database Developer,"Murkez Technologies · Lahore, Punjab, Pakistan...",Full-time,https://www.linkedin.com/jobs/view/3727034665,51-200 employees,3727034665,https://www.linkedin.com/jobs/view/3727034665,About the job\n \n\n \nCompany Over...,IT Services and IT Consulting\n \n ...
3,Business Intelligence Developer,"DevNatives · Islamabad, Islāmābād, Pakistan (H...",Full-time,https://www.linkedin.com/jobs/view/3727029273,11-50 employees,3727029273,https://www.linkedin.com/jobs/view/3727029273,About the job\n \n\n \nBI Developer...,IT Services and IT Consulting\n \n ...
4,Web Developer - Internship,"ItCreaters · Lahore, Punjab, Pakistan (On-site...",Full-time,https://www.linkedin.com/jobs/view/3727034696,Mobeen Naqvi is hiring for this job,3727034696,https://www.linkedin.com/jobs/view/3727034696,About the job\n \n\n \nIt is a prog...,NaN
...,...,...,...,...,...,...,...,...,...
27634,Technical Sales Support Specialist,"BUZZMAX.CA · Karāchi, Sindh, Pakistan \n1 wee...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3765162094,11-50 employees,3765162094,https://www.linkedin.com/jobs/view/3765162094,About the job\n \n \nABOUT US BUZZM...,Telecommunications\n \n ...
27635,YouTube Channel Producer,"Senew Tech · Lahore District, Punjab, Pakistan...",On-site\n\n \nFull-time,https://www.linkedin.com/jobs/view/3767643794,"501-1,000 employees",3767643794,https://www.linkedin.com/jobs/view/3767643794,About the job\n \n \nWe are seeking...,Information Technology & Services\n ...
27636,Social Media Content Creator - Night Shift wit...,"Dymentions Pakistan · Karāchi, Sindh, Pakistan...",On-site\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3769970428,11-50 employees · Marketing Services,3769970428,https://www.linkedin.com/jobs/view/3769970428,About the job\n \n \nJoin the Socia...,Marketing Services\n \n ...
27637,Design Sales agents,Self-employed · Pakistan \n1 week ago\n\n · 1...,Remote\n\n \nPart-time,https://www.linkedin.com/jobs/view/3766852400,Shayan Tauqeer is hiring for this job,3766852400,https://www.linkedin.com/jobs/view/3766852400,About the job\n \n \nCompany Descri...,NaN
27640,Manager – Growth Chat & SMS (Digital Marketing),"Bank Alfalah Limited · Karāchi, Sindh, Pakista...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3767355025,"5,001-10,000 employees · Banking",3767355025,https://www.linkedin.com/jobs/view/3767355025,About the job\n \n \nThis role is p...,NaN

In [27]:
# df_2[df_2['Job ID']==3769970428] for verification

#### using commen keywords used in IT and Tech

In [28]:
Software_Eng_keywords_all=['Software Engineer','Software Developer','Software/Application Developer','Software Development',
                           'Software Quality Assurance','Software Architect','Software Project Manager','QA',
                           'Software Test Engineer','Software Engineering','Software Trainee Engineer',
                           'Software Document Writer','Software Delivery Engineer','Software Support Manager',
                           'Product Specialist - Software Solutions',
                           'Software Services Lead','Software Project Coordinator',
                           'SDDC Consultant (Software-Defined Data Center)','Software Solutions Architect',
                           'Hardware/Software Tester','Software Support Engineer', 'Engineering Manager, GFI Software',
                           'Fellow of GenAI Software Excellence','Pre-Sales Software']
Software_Eng_keywords_all
len(Software_Eng_keywords_all)

filtered_df_3_title = df_3[df_3['Job Title'].apply(lambda title: any(keyword.lower() in title.lower() for keyword in Software_Eng_keywords_all))]
filtered_df_3_title

,Job Title,Job Info,Job Type,Job Link_x,employees,Job ID,Job Link_y,Job Desception,Company Info
122,Software Engineer,"Jin Technologies Private Limited · Islamabad, ...",Full-time,https://www.linkedin.com/jobs/view/3727035963,51-200 employees,3727035963,https://www.linkedin.com/jobs/view/3727035963,About the job\n \n\n \nFor our offi...,IT Services and IT Consulting\n \n ...
130,Software Engineer - Product Operation,"i2c Inc. · Lahore, Punjab, Pakistan (On-site) ...",Full-time,https://www.linkedin.com/jobs/view/3727020559,"1,001-5,000 employees",3727020559,https://www.linkedin.com/jobs/view/3727020559,About the job\n \n\n \ni2c is looki...,Financial Services\n \n ...
168,SOFTWARE DEVELOPER,"360 TECHNOLOGIES · Islamabad, Islāmābād, Pakis...",Full-time,https://www.linkedin.com/jobs/view/3727057491,51-200 employees,3727057491,https://www.linkedin.com/jobs/view/3727057491,About the job\n \n\n \nCompany Desc...,Information Technology & Services\n ...
185,Software Engineer,"Telenor · Islamabad, Islāmābād, Pakistan (On-s...",Full-time · Entry level,https://www.linkedin.com/jobs/view/3723693959,"10,001+ employees · Telecommunications",3723693959,https://www.linkedin.com/jobs/view/3723693959,About the job\n \n\n \nLast day to ...,Telecommunications\n \n ...
198,Software Quality Assurance Engineer,"Brickclay · Faisalabad, Punjab, Pakistan (On-s...",Full-time,https://www.linkedin.com/jobs/view/3727007394,51-200 employees,3727007394,https://www.linkedin.com/jobs/view/3727007394,About the job\n \n\n \nRoles and Re...,Information Technology & Services\n ...
...,...,...,...,...,...,...,...,...,...
27588,"Lead Software Engineer, Trilogy (Remote) - $10...","Crossover · Lahore, Punjab, Pakistan Reposted...",Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3766612589,"5,001-10,000 employees · IT Services and IT Co...",3766612589,https://www.linkedin.com/jobs/view/3766612589,About the job\n \n \nCrossover is t...,IT Services and IT Consulting\n \n ...
27598,"Senior C++ Software Engineer, GFI Software (Re...","Crossover · Lahore, Punjab, Pakistan Reposted...",Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3766356253,"5,001-10,000 employees · IT Services and IT Co...",3766356253,https://www.linkedin.com/jobs/view/3766356253,About the job,NaN
27615,QA Engineer,"NewRich Network · Lahore, Punjab, Pakistan \n...",Remote\n\n \nFull-time\n\n \nEntry level,https://www.linkedin.com/jobs/view/3772083919,11-50 employees · Online Audio and Video Media,3772083919,https://www.linkedin.com/jobs/view/3772083919,About the job\n \n \nWe are a compa...,Online Audio and Video Media\n \n ...
27627,"Principal Software Engineer, IgniteTech (Remot...","Crossover · Karāchi, Sindh, Pakistan Reposted...",Remote\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3766351795,"5,001-10,000 employees · IT Services and IT Co...",3766351795,https://www.linkedin.com/jobs/view/3766351795,About the job\n \n \nCrossover is t...,IT Services and IT Consulting\n \n ...
27632,Software Development Support Engineer (L2 & L3),"the ENTERTAINER · Lahore, Punjab, Pakistan \n...",On-site\n\n \nFull-time\n\n \nMid-Senior level,https://www.linkedin.com/jobs/view/3763867444,201-500 employees · Software Development,3763867444,https://www.linkedin.com/jobs/view/3763867444,About the job,NaN

In [29]:
filtered_df_3_title['Job Title'].unique()
# len(filtered_df_3_title['Job Title'].unique())

array(['Software Engineer', 'Software Engineer - Product Operation',
       'SOFTWARE DEVELOPER', 'Software Quality Assurance Engineer',
       'Senior Software Engineer', 'Software Engineer-Integration',
       'Professional, QA',
       'AI-Augmented Software Developer, Trilogy (Remote) - $200,000/year USD',
       'Senior Software Quality Assurance Engineer',
       'Software Development Engineer in Test (SDET)',
       'Software Developer', 'Software Engineer - Marketing Platform',
       'Senior QA Engineer',
       'Senior Software Development Project Manager',
       'Software Quality Assurance Analyst',
       'Software Architect Lead Developer',
       'Software Engineer (.Net/MVC)', 'Principal Software Engineer',
       'Senior Software Engineer (.NET/ React Js)',
       'Principal Software Engineer Full Stack PHP',
       'Senior Java Software Engineer',
       'Team Lead IT Software Development (m/f/d)',
       'AI-Augmented Software Developer, Skyvera (Remote) - $200,000/year USD',
       'Embedded Software Engineer',
       'Principal Software Engineer (khi/lhr/Isl)',
       'Software Engineer, Skyvera (Remote) - $200,000/year USD',
       'Software/Application Developer', 'Software Engineer (React js)',
       'Software Development Engineer, Trilogy (Remote) - $100,000/year USD',
       'Hybrid QA for financial software',
       'Software Engineer with AI Tooling Expertise, Skyvera (Remote) - $200,000/year USD',
       'Senior Software Engineering Manager',
       'Senior Software Engineer - Node',
       'Senior C++ Software Engineer, Trilogy (Remote) - $200,000/year USD',
       'Lead Software Engineer', 'Java Software Engineer',
       'Software Engineer II- Android',
       'Sr. Software Engineer - OpenSIPS', 'C++ Software Engineer II',
       'Senior Software Developer', 'Civil Engineers (Roads, QA/QC) QS',
       'Software Engineer - Angular', 'SQA Engineer',
       'Senior C++ Software Engineer', 'Software Development Engineer',
       '🚀 Seeking a Talented Angular Software Developer to Join Our Startup Team!',
       'Software Development Team Leader', 'ODOO Software Developer',
       'Software Engineer - iOS', 'Senior SQA Engineer - Automation',
       'Principal Software Quality Assurance Engineer',
       'SQA Engineer - Mobile', 'Front-End Software Engineer',
       'Senior Principal Software Engineer, Trilogy (Remote) - $100,000/year USD',
       'Software Engineer (AI-Powered Development), Trilogy (Remote) - $200,000/year USD',
       'Senior Software Architect, Trilogy (Remote) - $100,000/year USD',
       'Chief Software Architect, gt.school (Remote) - $200,000/year USD',
       'Lead Software Engineer, Trilogy (Remote) - $100,000/year USD',
       'Senior Software Engineer, Trilogy (Remote) - $200,000/year USD',
       'Principal Software Engineer, Trilogy (Remote) - $100,000/year USD',
       'Principal Software Architect, gt.school (Remote) - $200,000/year USD',
       'Principal Software Engineer, GFI Software (Remote) - $100,000/year USD',
       'Principal Software Engineer, gt.school (Remote) - $100,000/year USD',
       'Senior Software Engineer, Trilogy (Remote) - $100,000/year USD',
       'Lead Software Engineer, gt.school (Remote) - $200,000/year USD',
       'Senior Software Engineer IV',
       'Senior Software Engineer - Flutter', 'Senior SQA Engineer',
       'Senior Software Engineer (Backend)', 'SQA',
       'Senior C++ Software Engineer, GFI Software (Remote) - $100,000/year USD',
       'Security Software Engineer - Blockchain / Web3',
       'Software Engineer- Mobile (Android)', 'Software Engineer, QA',
       'Software Engineer Frontend', 'Lead Software Engineer - React JS',
       'Senior Software Engineer - Ruby on Rails',
       'Associate Software Architect', 'Associate SQA Engineer',
       'Junior Software Quality Assurance Engineer',
       'Software Project Manager', 'Sr.SQA Engineer',
       'Software Architect', 'Hybrid QA for financial software 2',
       'SQA Engineer (Team Lead)', 'C# .NET Software Engineer',
       'Principal Software Engineer, gt.school (Remote) - $200,000/year USD',
       'Head of Software Engineering (Python)',
       'Software Engineer - Blockchain / Web3 - APAC',
       'Senior Software Engineer (.Net)',
       'Java / Angular Software Developer - +3 years - Contractor in USD',
       'Software Delivery Engineer', 'QA Engineer',
       'Software Engineering Manager',
       'Senior Back-End Software Engineer',
       'Senior Android Software Engineer', 'QA Engineer - Manual',
       'Software Engineer - React Native',
       'Principal Software Engineer - Ruby on Rails',
       'Principle Software Engineer (Frontend)',
       'Software Engineer III-Django', 'QA Engineer - Mobile',
       'Software Architect - Python',
       'Software Quality Assurance Manager',
       'Sr. Software Engineer (.NET)', 'System Software Engineer',
       'Software Engineering Manager, Trilogy (Remote) - $100,000/year USD',
       'Software Architect, gt.school (Remote) - $100,000/year USD',
       'Sr. SQAE Automation', 'Senior Software Engineer (Fullstack)',
       'Full Stack Lead Software Engineer', 'SQA Analyst',
       'Software Quality Assurance (Manual) - Pakistan',
       'Senior Software Engineer - Java Spring Boot (4-7 years)',
       'Software Engineer - .NET & C#',
       'Cybersecurity Software Developer',
       'Business Development Manager (Software Development Services)',
       'Senior Software Engineer/Fullstack',
       'Senior Software Development Engineer in Test - Data Analytics',
       'Software Developer in Test', 'Quality Assurance (QA) Specialist',
       'Principal Software Engineer (Backend)',
       'Software Development  Manager',
       'Senior Software Engineer Team Lead', 'Software Test Engineer',
       'Remote Software Job | Software Development And Design',
       'Senior Software Engineer (AI/Infra)',
       'Software Architect (JAVA MVC Springboot)',
       'Senior Software Engineer (Vue.js)', 'PS Software Engineer',
       'Sr. SQA Automation Engineer', 'Software Engineer (Full Stack)',
       'Senior Software Engineering Manager, Trilogy (Remote) - $100,000/year USD',
       'Mobile Apps (Xamarin) - Software Developer',
       'Software Engineer .Net & iOS',
       'Senior Software Engineer - .NET (6-months contract)',
       'Senior Software Engineer (GoLang)',
       'Senior Software Engineer - Backend Developer',
       'Staff Software Engineer', 'Senior Software Engineer - UI',
       'Senior Software Engineer - Angular', 'Fintech Software Developer',
       'Software Support Manager',
       'Software Architect, Trilogy (Remote) - $100,000/year USD',
       'Software Engineer [iOS]', 'Software Engineer- MEAN',
       'Senior Software Developer-  Angular', 'Software Engineer II',
       'Senior Software Development Engineer Test',
       'Software Engineer - ROR', 'Software Engineer (m/f/d)',
       'Trainee Software Developer', 'Software Engineer (.Net/React)',
       'Software Engineer (Front End)', 'SQA Manager/ Team Lead SQA',
       'Full Stack Software Engineer',
       'Intermediate Software Developer(winForms/WPF)',
       'Senior Software Engineer/CRM',
       'Senior Software Engineer - Angular (H-216)',
       'Junior Software Engineer', 'Junior SQA Analyst',
       'Senior Software Engineer - iOS', 'QA Automation Engineer II',
       'Senior Software Engineer (PHP)', 'Software Engineer - Front End',
       'Specialist Software Engineer',
       'Software Engineer - Node (H-218-01)',
       'Employee Service Executive - Port Qasim (H-164)',
       'Senior Software Engineer - Back-End',
       'Employee Service Executive - Qasba Gujrat (H-164)',
       'Principal Software Engineer - Front End',
       'Senior Software Engineer - React',
       'Senior Software Engineer - .NET',
       'WordPress/PHP (Back-end) Software Engineer',
       'Software Engineer (.Net/React Js)',
       'Senior Software Quality Assurance (Test Automation) - Pakistan',
       'Software Development Manager',
       'AI Software Quality Assurance Engineer', 'QA Automation Engineer',
       'Software Engineer - JAVA', 'Associate Software Engineer',
       'Phone Messaging Apps Urdu (Pakistan) Language QA Reviewer',
       'Sr Software Engineer (EHR Integration Specialist)',
       'Product Specialist - Software Solutions (Microsoft, Symantec, ESET)',
       'Software Quality Assurance Engineer(Automation + Manual)',
       'Software Services Lead',
       'Principal/ Staff Software Engineer - NodeJS+NestJS+AWS (Afternoon Shift)',
       'Sr. Software Quality Assurance Engineer',
       'Software Project Coordinator', 'Software Engineer - WordPress',
       'Senior Software Quality Assurance Specialist',
       'Back End Software Engineer',
       'Javascript (React/Node) Software Developer (Pakistan)',
       'SQA Automation Engineer', 'SQA Automation Analyst',
       'Software Development Manager JAVA',
       'Software Development Project Manager and Recruitment Officer',
       'Senior Software Engineer - Laravel', 'Software Document Writer',
       'Software Engineer (.net stack)', 'Head of Software Engineering',
       'SDDC Consultant (Software-Defined Data Center)',
       'Senior Software Tester - QA - Onsite role - NIGHT SHIFT',
       'Software Engineering Team Lead (with web3 experience)',
       'Senior Software Engineer .Net Core', 'Lead Software Architect',
       'Software Solutions Architect',
       'Junior Software Engineer, Trilogy (Remote) - $60,000/year USD',
       'Principal Software Engineer .Net+Angular',
       'Software Development Engineer, Trilogy (Remote) - $60,000/year USD',
       'Specialist ERP & Software Development',
       'Software Engineer .NET - .NET to CRM',
       'Software Developer, Skyvera (Remote) - $30,000/year USD',
       'Full Stack Developer (Software Engineer, MEAN/MERN)',
       'Hardware/Software Tester',
       'Software Architect, IgniteTech (Remote) - $100,000/year USD',
       'Lead Software Engineer, IgniteTech (Remote) - $100,000/year USD',
       'Senior Principal Software Engineer, IgniteTech (Remote) - $100,000/year USD',
       'Senior Software Engineer - WordPress & PHP Project',
       'Senior Software Engineer C++',
       'Software Engineering Manager, IgniteTech (Remote) - $100,000/year USD',
       'Principal Software Engineer, IgniteTech (Remote) - $100,000/year USD',
       'Hybrid QA for financial software 3', 'Software Engineer-iOS',
       'Senior Software Engineer - Big Data',
       'Lead Software Quality Assurance Engineer', 'Junior QA Analyst',
       'Senior Software Engineer - Team Lead',
       'Sr. Software Engineer-Team Lead', 'Software Engineer Team Lead',
       'Crypto QA Automation Engineer Intern (Pakistan-Remote)',
       'Senior Software Engineer PHP',
       'Software Development Specialist, Skyvera (Remote) - $30,000/year USD',
       'Mid Level Software Developer',
       'QA Engineer – Insights and Analytics',
       'Software Quality Assurance (SQA) Engineer',
       'QA Engineer (Salesforce - CRM)',
       'Principal Software Engineer - iOS', 'Software Trainee Engineer',
       'Project Manager Software Development',
       'Junior Software Engineer, Skyvera (Remote) - $30,000/year USD',
       'Software Engineer II - Backend', 'Data Tester / BI QA',
       'Hybrid QA for financial software 4',
       'Senior Software Engineer (Back-End)', 'Software Engineer (.Net)',
       'Senior Software Engineer - React Native',
       'Expert Software Engineer',
       'Senior Software Engineer (GoLang, PHP)',
       'Senior Software Engineer (.NET)',
       'Sr. Software Engineer Mobile(React Native)',
       'Head of AI-driven Software Development, Trilogy (Remote) - $400,000/year USD',
       '.NET / Azure Cloud Expert Software Engineer - Full Remote - Contractor in USD',
       'Deputy Manager Software Development',
       'Head of Software Development (AI-Enhanced Processes), Trilogy (Remote) - $400,000/year USD',
       'Software Engineer, Trilogy (Remote) - $60,000/year USD',
       'Senior SQA Automation Engineer', 'ORACLE SOFTWARE DEVELOPER',
       'Principal Software Engineer - Android',
       'Senior Software Engineer, GFI Software (Remote) - $100,000/year USD',
       'Software Engineer - Node.js',
       'Software Developer (Laravel/PHP/JS)',
       'Senior Software Engineer - .Net Core',
       'Pre-Sales Software Engineer', 'Sr Software Engineer (MERN+AWS)',
       'Senior Software Engineer (PHP, GoLang)',
       'Senior Software Development Engineer in Quality Engineering',
       'Sr. Software Engineer - UI', 'Software Engineer Intern',
       'Software Support Engineer - L2', 'Software Developer - Java',
       'Software Engineer (PHP)', 'Software Quality Assurance Specialist',
       'Software Engineer - Laravel',
       'Senior QA Analyst - Web Development - Contractor in USD',
       'Senior Lead Software Engineer, Trilogy (Remote) - $100,000/year USD',
       'Director of AI - Enhanced Software Development, Trilogy (Remote) - $400,000/year USD',
       'Team Lead IT Software Development (m/f/d) - 100% remote',
       'Sr SQA Engineer (On-Site)', 'Software Engineer, DevOps',
       'Software Architect (.NET) - Onsite (Lahore)',
       'Software Support Engineer, IgniteTech (Remote) - $60,000/year USD',
       'QA Software Automation Engineer',
       'Principal Software Engineer - Frontend', 'Senior Manager QA',
       'QA Test Automation Engineer',
       'Senior Software Engineer - Android',
       'Senior Software Engineer - IOS',
       'Senior Engineering Manager, GFI Software (Remote) - $100,000/year USD',
       'Program Officer - SBCC - Qadam Ba Qadam Project',
       'Regional SQA Analyst',
       'Principal Software Engineer – Microsoft Dynamics CRM',
       'Technical Advisor - Family Planning - Qadam Ba Qadam Project',
       'Senior Software Engineer – Microsoft Dynamics CRM',
       'Program & Administrative Assistant - Qadam Ba Qadam Project',
       'Administrative Assistant - Qadam Ba Qadam Project',
       'Social Behavior Change Communication Specialist - Qadam Ba Qadam Project',
       'Staff Software Engineer, Trilogy (Remote) - $200,000/year USD',
       'Software Engineering Manager, GFI Software (Remote) - $100,000/year USD',
       'Senior Software Engineer (Laravel & 3rd party Integrations)',
       'Senior Software Engineer - .NET+Angular',
       'Senior Software Architect, Trilogy (Remote) - $200,000/year USD',
       'Senior Software Engineer - React JS',
       'Lead Software Engineer, Trilogy (Remote) - $200,000/year USD',
       'Fellow of GenAI Software Excellence, Trilogy (Remote) - $400,000/year USD',
       'Jr. Software Quality Assurance Engineer',
       'Frontend Software Developer', 'Software Engineer SQA',
       'Senior Software Engineer - SharePoint',
       'Software Engineer_Node JS', 'Pre-Sales Software',
       'Software Development Support Engineer (L2 & L3)'], dtype=object)

In [30]:
titles_to_drop_old=['Civil Engineers (Roads, QA/QC) QS','Business Development Manager (Software Development Services)']

In [31]:
Un_QA_titles=['Technical Advisor - Family Planning - Qadam Ba Qadam Project','Program & Administrative Assistant - Qadam Ba Qadam Project',
              'Administrative Assistant - Qadam Ba Qadam Project',
              'Social Behavior Change Communication Specialist - Qadam Ba Qadam Project',
              'Employee Service Executive - Qasba Gujrat (H-164)','Professional, QA']
Un_QA_titles

['Technical Advisor - Family Planning - Qadam Ba Qadam Project',
 'Program & Administrative Assistant - Qadam Ba Qadam Project',
 'Administrative Assistant - Qadam Ba Qadam Project',
 'Social Behavior Change Communication Specialist - Qadam Ba Qadam Project',
 'Employee Service Executive - Qasba Gujrat (H-164)',
 'Professional, QA']

In [32]:
titles_to_drop=titles_to_drop_old+Un_QA_titles
titles_to_drop
len(titles_to_drop)

8

In [34]:
df_3_Software_Eng=filtered_df_3_title[~filtered_df_3_title['Job Title'].isin(titles_to_drop)]
df_3_Software_Eng
len(df_3_Software_Eng)
len(df_3_Software_Eng['Job Title'].unique())

304

In [36]:
df_3_Software_Eng.to_csv('Filltered_Files/software_engineer_26_sep_to_26_nov_735_jobs_304_titles_v5.csv',index=False)

import pandas as pd

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
it_tech_pattern = 'IT|Tech'
filtered_df = df[df['job_title'].str.contains(it_tech_pattern, case=False)]

import pandas as pd

it_tech_keywords = ['IT', 'Tech', 'Information Technology', 'Developer', 'Software Engineer', 'Data Scientist', ...]

# Assuming your DataFrame is named 'df' and the job titles are in a column 'job_title'
filtered_df = df[df['job_title'].apply(lambda title: any(keyword in title for keyword in it_tech_keywords))]